import sys

file_path = r"d:\site\jinydev\Statistical\src\book\c03\3_3_other_considerations_in_the_regression_model\3_3_1_qualitative_predictors\3_3_1_1_predictors_with_only_two_levels\index.md"
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "Suppose that we wish to investigate differences in credit card balance between those who own a house and those who don’t, ignoring the other variables for the moment. If a qualitative predictor (also known as a _factor_ ) factor only has two _levels_ , or possible values, then incorporating it into a regres- level sion model is very simple. We simply create an indicator or _dummy variable_ dummy that takes on two possible numerical values.[10] For example, based on the variable `own` variable, we can create a new variable that takes the form":
    "Suppose that we wish to investigate differences in credit card balance between those who own a house and those who don’t, ignoring the other variables for the moment.\n당분간 여타의 다른 변수들은 덮어두고, 단지 자가를 소유한 집단과 그렇지 않은 대조군 사이의 신용카드 잔고 내역 차이를 집중적으로 심층 조사해 탐구하고자 한다고 가정해 봅시다.\n\nIf a qualitative predictor (also known as a _factor_) only has two _levels_, or possible values, then incorporating it into a regression model is very simple.\n어떤 정성적 예측 변수(때로는 _요인(factor)_ 이라 불리기도 함)가 오직 두 개의 단일 _수준(levels)_ 내지는 두 가닥의 발생 가능한 값을 가지는 경우라면, 이를 통계적 회귀 모델에 합병 편입시키는 일은 정말이지 매우 간단합니다.\n\nWe simply create an indicator or _dummy variable_ that takes on two possible numerical values.[10]\n우리는 통상 두 가지 방향의 지수형 숫자형 값을 자체 취하는 모종의 지표 지시자 함수나 특수 _더미 변수(dummy variable)_ 체계를 신속히 고안해 창출해 내면 그만이기 때문입니다.[10]\n\nFor example, based on the `own` variable, we can create a new variable that takes the form",
    
    "and use this variable as a predictor in the regression equation. This results in the model":
    "and use this variable as a predictor in the regression equation.\n그리고 이렇게 손수 고안해 창출한 특수 변수를 회귀 방정식 체제 하의 예측 인자로 사용합니다.\n\nThis results in the model",
    
    "Now \beta_0 can be interpreted as the average credit card balance among those who do not own, \beta_0 + \beta_1 as the average credit card balance among those who do own their house, and \beta_1 as the average difference in credit card balance between owners and non-owners.":
    "Now $\\beta_0$ can be interpreted as the average credit card balance among those who do not own, $\\beta_0 + \\beta_1$ as the average credit card balance among those who do own their house, and $\\beta_1$ as the average difference in credit card balance between owners and non-owners.\n이제 여기서 모수 $\\beta_0$ 항은 자가 소유 체제를 유지하지 않는 대조군 집단 내 신용카드 평균액 잔고를 대표하는 것으로 꽤 수월하게 의미 해석될 수 있고, $\\beta_0 + \\beta_1$ 수식 범위는 실제로 자기 소유 자택을 버젓이 점유한 유주택 집단군의 평균 지출 신용카드 잔고를 대변하며, 마지막으로 $\\beta_1$ 상수는 전자인 주택 보유 측과 후자인 미보유 대조군 양측 사이의 신용카드 지출 잔고 액수 격차의 단편적 평균을 암시하는 것으로 풀이해 간주될 수 있습니다.",
    
    "Table 3.7 displays the coefficient estimates and other information associated with the model (3.27). The average credit card debt for non-owners is estimated to be $509 _._ 80, whereas owners are estimated to carry $19 _._ 73 in additional debt for a total of $509 _._ 80 + $19 _._ 73 = $529 _._ 53. However, we":
    "Table 3.7 displays the coefficient estimates and other information associated with the model (3.27).\n표 3.7 은 모델 체계 (3.27) 에 관련된 계수 추정치 및 여타 종류의 여분 정보 사항들을 직접적으로 알기 쉽도록 나타냅니다.\n\nThe average credit card debt for non-owners is estimated to be $\\$509.80$, whereas owners are estimated to carry $\\$19.73$ in additional debt for a total of $\\$509.80 + \\$19.73 = \\$529.53$.\n주택 미보유 계층군의 평균 집계 신용카드 부채 액수 단락은 대략 $\\$509.80$ 로 추산되는 반면, 실제 유주택자층 소유 대상자들은 저마다 개별적으로 총계 비용 $\\$509.80 + \\$19.73 = \\$529.53$ 수위에 육박하는, 다시 말해 무주택자에 비해 대략 $\\$19.73$ 만큼의 채무를 평균치 구도로 더 부담하는 것으로 간주됩니다.\n\nHowever, we",
    
    "> 10In the machine learning community, the creation of dummy variables to handle qualitative predictors is known as “one-hot encoding”.":
    "> [10] In the machine learning community, the creation of dummy variables to handle qualitative predictors is known as \"one-hot encoding\".\n> [10] 기계 학습(machine learning) 관련 학계 내에서 이처럼 특정 정성적 구도 속성을 띤 예측 변수를 포섭하고 취급하고자 의도적으로 더미 변수 단위를 창출하는 제반 행위를 가리켜 통상 \"원-핫 인코딩(one-hot encoding)\" 이라 명명해 지칭합니다.",
    
    "92 3. Linear Regression": "",
    
    "notice that the $p$-value for the dummy variable is very high. This indicates that there is no statistical evidence of a difference in average credit card balance based on house ownership.":
    "notice that the $p$-value for the dummy variable is very high. This indicates that there is no statistical evidence of a difference in average credit card balance based on house ownership.\n그런데 막상 더미 변수 척도에 해당하는 그 $p$-값은 매우 크다는 단편적 사실을 발견하게 됩니다. 이는 결국 자가 주택 소유 여부 판별에 따른 모종의 평균 신용카드 잔고 지표 간에 그 어떤 뚜렷한 실제 격차도 사실상 통계적으로 존재하지 않는다는 증거 부족의 실상을 시사합니다.",
    
    "The decision to code owners as 1 and non-owners as 0 in (3.27) is arbitrary, and has no effect on the regression fit, but does alter the interpretation of the coefficients. If we had coded non-owners as 1 and owners as 0, then the estimates for \\beta_0 and \\beta_1 would have been 529 _._ 53 and _−_ 19 _._ 73, respectively, leading once again to a prediction of credit card debt of $529 _._ 53 _−_ $19 _._ 73 = $509 _._ 80 for non-owners and a prediction of $529 _._ 53 for owners. Alternatively, instead of a 0 _/_ 1 coding scheme, we could create a dummy variable":
    "The decision to code owners as $1$ and non-owners as $0$ in (3.27) is arbitrary, and has no effect on the regression fit, but does alter the interpretation of the coefficients.\n(3.27) 식 상에서 자택 소유자를 $1$ 로, 미소유자 군을 각각 $0$ 으로 암호 체계 부호화하여 할당한다는 식의 단순 결정 자체는 어디까지나 다분히 임의적이며, 그 때문에 이것이 회귀 적합 구성 전반에 미치는 실제 파급 효과란 사실상 아예 없지만 제반 계수의 통계적 의미를 풀이하는 체제 부분 관점에서는 다소 유의미한 해석 변동을 불러일으킬 뿐입니다.\n\nIf we had coded non-owners as $1$ and owners as $0$, then the estimates for $\\beta_0$ and $\\beta_1$ would have been $529.53$ and $-19.73$, respectively, leading once again to a prediction of credit card debt of $\\$529.53 - \\$19.73 = \\$509.80$ for non-owners and a prediction of $\\$529.53$ for owners.\n만일 처음부터 우리가 반대로 주택 미보유층 집단 부호를 $1$ 로 지정하고 실소유주를 $0$ 부호로 코드화했더라면, 각각의 $\\beta_0$ 와 $\\beta_1$ 모수 추산치 단위값 구성은 지금과는 다른 별개의 $529.53$ 과 $-19.73$ 이 됨으로써, 결과론적으로 보아 다시 또 동일하게 주택 미소유자의 신용카드 부채 채무액 규모 추정치는 $\\$529.53 - \\$19.73 = \\$509.80$ 이 될 테고 자가 보유층 집단이 갖게 될 예측치는 고스란히 예전 그대로의 형상인 $\\$529.53$ 이 전개 도출될 것입니다.\n\nAlternatively, instead of a $0 / 1$ coding scheme, we could create a dummy variable",
    
    "and use this variable in the regression equation. This results in the model":
    "and use this variable in the regression equation.\n그리고 이렇게 형성한 허구의 더미 변수 모델을 고스란히 회귀 방정식 구절로 채택하여 이용할 수도 있습니다.\n\nThis results in the model",
    
    "Now \\beta_0 can be interpreted as the overall average credit card balance (ignoring the house ownership effect), and \\beta_1 is the amount by which house owners and non-owners have credit card balances that are above and below the average, respectively.[11] In this example, the estimate for \\beta_0 is $519 _._ 665, halfway between the non-owner and owner averages of $509 _._ 80 and $529 _._ 53. The estimate for \\beta_1 is $9 _._ 865, which is half of $19 _._ 73, the average difference between owners and non-owners. It is important to note that the final predictions for the credit balances of owners and non-owners will be identical regardless of the coding scheme used. The only difference is in the way that the coefficients are interpreted.":
    "Now $\\beta_0$ can be interpreted as the overall average credit card balance (ignoring the house ownership effect), and $\\beta_1$ is the amount by which house owners and non-owners have credit card balances that are above and below the average, respectively.[11]\n이제 이 구도상 모수 $\\beta_0$ 속성은 아예 주택의 실질 소유 유무별 부가 요인 후광 파급력을 배제 통제하고 간과한 채 지극히 포괄적인 형식의 전체적인 범주를 대변하여 나타내는 통계상 전반적 평균치 신용 잔고 자산 규모라 일일이 이해될 수 있으며, 그에 맞붙은 옆 부분 $\\beta_1$ 은 주택 실소유자군 대조 패널과 또 미보유 계층별 집단들 각각의 총 신용 자산 잔금이 방금 언급한 그 포괄적 평균 기준 대비 실제 어느 수준만큼 위아래로 얹혀 오르내리는지 차감 액수 수준의 간격을 드러내는 구도 물량입니다.[11]\n\nIn this example, the estimate for $\\beta_0$ is $\\$519.665$, halfway between the non-owner and owner averages of $\\$509.80$ and $\\$529.53$.\n이 사례 모델 형식상 $\\beta_0$ 추정치는 거진 $\\$519.665$ 정도로 도출되는데, 정확하게 이 값은 주택 미소유자의 평균대인 $\\$509.80$ 와 보유군 평균 지표인 $\\$529.53$ 그 두 극단의 한복판 정중앙치 구심점에 귀결되어 안착합니다.\n\nThe estimate for $\\beta_1$ is $\\$9.865$, which is half of $\\$19.73$, the average difference between owners and non-owners.\n또한 추가로 덧붙여 $\\beta_1$ 항의 관련 모수 추정치 역시 어림잡아 $\\$9.865$ 정도로 나타나는데, 이는 두 양단 집단 소유군 및 미소유자층 간의 실제 전체 평균 격차 척도로 관측된 액수 $\\$19.73$ 량의 정확히 절반을 뚝 잘라 양분한 반토막 조각 치수와 판에 박은 듯 상동한 수준 액수 지표입니다.\n\nIt is important to note that the final predictions for the credit balances of owners and non-owners will be identical regardless of the coding scheme used.\n여기서 우리가 놓치지 않고 눈여겨 주의 깊게 살펴 기약해야 할 주안점 특이 사항은, 궁극적으로 자택 보유 여력별 소유군 및 무소유 계층 각각 개체를 조준하여 실체가 도출된 끝맺음 귀결 예측 결과치 신용 잔고 산출 물량이 애초 사용자가 어떤 식으로 앞선 부호 인코딩 체계 척도를 차용해 지정 조작했건 상관하지 않고 끝에는 매양 동등하게 획일적 동일 양태 결과 치수로 전방위 수렴된다는 불변적 사실입니다.\n\nThe only difference is in the way that the coefficients are interpreted.\n결국 발생하게 되는 이견 차이란 단지 개별 계수 요인 하나하나가 통계 관점으로 의미 도출 풀이 적용 및 해석 처리되는 세세한 방법론 그 체계 관점 노선 하나뿐이기 때문입니다.",
    
    "When a qualitative predictor has more than two levels, a single dummy variable cannot represent all possible values. In this situation, we can create additional dummy variables. For example, for the `region` variable we create two dummy variables. The first could be":
    "When a qualitative predictor has more than two levels, a single dummy variable cannot represent all possible values.\n만약 모종의 정성적인 예측 변수가 포섭해 지닌 등급 수준(levels) 값이 단순히 2개를 초과하여 형성된 다분화 구조일 경우라면, 일명 단일한 속성의 더미 변수 구조 체계 딱 하나만 가지고서는 현실적으로 이 모든 발생 가망 가능한 복잡 범주 지표 값을 다 망라할 수는 없습니다.\n\nIn this situation, we can create additional dummy variables.\n바로 이러한 경우, 우리는 얼마든지 몇 배구 추가 여건 부수 더미 변수 부품 조각들을 거뜬히 잇달아 고안해 생성해 내면 그뿐입니다.\n\nFor example, for the `region` variable we create two dummy variables. The first could be\n예컨대, 특정 구역 지표군을 관통해 가르지르는 `region(지역)` 예측 변수가 있다 치면, 당분간 우리는 이를 위해 가상의 더미 변수 표본 둘을 즉시 창안 축조해 둘 수 있습니다. 그중 첫 번째 변수 체제 형태는 필경 아래와 같을 것입니다.",
    
    "and the second could be":
    "and the second could be\n그리고 두 번째의 경우 이내 다음과 같은 형식 형체가 될 수 있을 것입니다.",
    
    "Then both of these variables can be used in the regression equation, in order to obtain the model":
    "Then both of these variables can be used in the regression equation, in order to obtain the model\n이후 이렇게 도출 준비된 이 두 여건 부수 변수 항목 전부를 한데 나란히 선형 체계 회귀 방정식 문맥 속에 묶어 투사 응용 활용할 수 있으며, 이내 그 수고 결과물로 차기 적합 모델 모형을 아래 구도로 온전히 취득하게 됩니다.",
    
    "Now \\beta_0 can be interpreted as the average credit card balance for individuals from the East, \\beta_1 can be interpreted as the difference in the average balance between people from the South versus the East, and \\beta_2 can be interpreted as the difference in the average balance between those from the West versus the East. There will always be one fewer dummy variable than the number of levels. The level with no dummy variable—East in this example—is known as the _baseline_ .":
    "Now $\\beta_0$ can be interpreted as the average credit card balance for individuals from the East, $\\beta_1$ can be interpreted as the difference in the average balance between people from the South versus the East, and $\\beta_2$ can be interpreted as the difference in the average balance between those from the West versus the East.\n이제 막 생성 적합 완료된 새 모형 전개 구조 내에서 거론된 중심 모수 $\\beta_0$ 의미는 오로지 특정 지역권인 동부(East) 출신에 호적 영토를 두고 머무는 개별 표본 집단 체계의 전박적인 평균 보유율 신용카드 적립 잔고액 규모 단편 수준치로 꽤 명맥하게 풀이해 석명될 수 있고, $\\beta_1$ 단락의 경우는 기실 동부(East)권 토박이 거주 층 대비 남부(South) 지역 체계 출신자 그룹의 평균 자산 잔고 수준이 상호 어느 일정 간극만큼 벌어져 있는지 양자 간 상충 격차 그 자체 지표를 꽤 투명히 가리킨 것으로 관점 해석되며, 끝으로 남은 항 $\\beta_2$ 체계 또한 마찬가지 관점에서 남부 대신 서부(West) 거주 계층이 동부권 토박이들 대비 실제 벌려 양산해 내는 평균 잔고치 상대 전용 이견 격차 지수 폭으로 가시 분간해 풀이해 판단지을 수 있습니다.\n\nThere will always be one fewer dummy variable than the number of levels.\n여기서 또 하나 눈겨겨볼 절대 규칙 중 진리 하나로 꼽자면 상시 구조적으로 투여될 전체의 가상 더미 변수 투입 개수 지표는 기저 태생부터 이미 변수가 거느릴 세부 특정 등급(levels) 구분 기준 총체적 범주 가짓수 부피에서 매번 매양 언제나 적확히 딱 '1' 이란 수치 만큼만 상시 체감 차감해 공제된 단편적 개수 비율로 제한 구성된다는 사실성입니다.\n\nThe level with no dummy variable — East in this example — is known as the _baseline_.\n이렇듯 해당 사례 모델 구상 안에서 별반 여벌 더미 구도 변수를 고유로 따로 소유하지조차 않고 동떨어져 혼자 남겨진 저 외로운 속성의 동부(East) 거점 지역과 같은 해당 무소속 등급 수준 잣대를 통계상 일명 특정 기초 기준점 요소라는 의미 차원의 _기준선(baseline)_ 범주라 칭합니다.",
    
    "> 11Technically \\beta_0 is half the sum of the average debt for house owners and the average debt for non-house owners. Hence, \\beta_0 is exactly equal to the overall average only if the two groups have an equal number of members.":
    "> [11] Technically $\\beta_0$ is half the sum of the average debt for house owners and the average debt for non-house owners. Hence, $\\beta_0$ is exactly equal to the overall average only if the two groups have an equal number of members.\n> [11] 기술적인 맥락 측면상 기저 $\\beta_0$ 지표 수치는 앞서 다룬 자가 보유 주택 여력자 층의 평균 채무 단위와 반대되는 미보유 층 전체의 평균 부채 지표 총합산 값을 반절로 등분 나눈 값입니다. 그렇기에 해당 부문 $\\beta_0$ 치수는 필연적으로 그 두 대조군 속성 그룹 양쪽 개체 지표 구성원 인원 숫자 비율 규모가 둘 다 완벽할 만치 철두철미 상호 동일한 극히 제약 균등 상태인 경우라는 일정한 제한 조건에서만 본디 오리지널 전체 획일적 포괄 평균 수치 단락에 정확무오하게 곧이 일치 귀결하여 떨어집니다.",
    
    "baseline": "",
    "100 3. Linear Regression": "",
    "|3. Linear Regression|3. Linear Regression|": "",
    
    "From Table 3.8, we see that the estimated `balance` for the baseline, East, is $531 _._ 00. It is estimated that those in the South will have $18 _._ 69 less debt than those in the East, and that those in the West will have $12 _._ 50 less debt than those in the East. However, the $p$-values associated with the coefficient estimates for the two dummy variables are very large, suggesting no statistical evidence of a real difference in average credit card balance between South and East or between West and East.[12] Once again, the level selected as the baseline category is arbitrary, and the final predictions for each group will be the same regardless of this choice. However, the coefficients and their $p$-values do depend on the choice of dummy variable coding. Rather than rely on the individual coefficients, we can use an _F_ -test to test $H_0$ : \\beta_1 = \\beta_2 = 0; this does not depend on the coding. This _F_ -test has a $p$-value of 0 _._ 96, indicating that we cannot reject the null hypothesis that there is no relationship between `balance` and `region` .":
    "From Table 3.8, we see that the estimated `balance` for the baseline, East, is $\\$531.00$.\n먼저 표 3.8 데이터 항목에 기저해 우리가 바로 당장 직관 도출 가능한 현상으론 기준군 기반 베이스라인 잣대로 삼은 대상인 동부권(East) 전역 할당 평균치 추정 `balance` 궤적이 대략 $\\$531.00$ 단위로 계측 구사되었다는 점입니다.\n\nIt is estimated that those in the South will have $\\$18.69$ less debt than those in the East, and that those in the West will have $\\$12.50$ less debt than those in the East.\n이와 비례하여 남부(South) 지방 세대 계층 군은 기준점 동부 층 토박이들보다 어림짐작상 상대 부채 지출 규모가 $\\$18.69$ 만큼 덜 초과 빚진 형국일 거라 예측 산출된 반면, 서부권(West) 층 군의 부채 단위 또한 동부권 대조군치보다 평균 $\\$12.50$ 수준가량 소폭 더 낮게 하락 도출되었다 거진 추정 평가됩니다.\n\nHowever, the $p$-values associated with the coefficient estimates for the two dummy variables are very large, suggesting no statistical evidence of a real difference in average credit card balance between South and East or between West and East.[12]\n그러나 위 두 대립 더미 변수에 소속된 저마다의 각 모수 계수 산출 추정치 궤도와 관련 맞물려 상호 연관 도출된 $p$-값 크기 단위 규모는 의외로 몹시 크고 방대하다는 걸 알 수 있는데, 막상 실상을 들여다보면 실상 이는 정작 남부-동부 혹은 서부-동부 두 극단 대조 지역 간 상호 발생하고 있을 만한 실제 카드 빚 평균치 간의 무언가 확연 타당한 유의미 그 실체 격차를 통계학적 진단 논리상 뚜렷이 밝혀내 확증해 줄 그 어떠한 뚜렷한 진배 다름의 실재 증거는 사실상 도무지 없다는 허무한 지적 난관적 결론을 대놓고 지지하며 암시하고 있습니다.[12]\n\nOnce again, the level selected as the baseline category is arbitrary, and the final predictions for each group will be the same regardless of this choice.\n다시 한 번 주지하건대, 당초 특수 기준 베이스라인(baseline) 그룹 관할 등급 범주로서 초기 선택 선별 채택되었던 어느 한 수준의 특정 타깃이 과연 누구인지 자체는 사실상 지극히 다분히 자의적 성향이 강할 수밖에 없고, 최종 결과치에 속할 그 어느 단일 각 개별 고유 그룹 관점의 종점 예측 결과 역시 이런 일개 사사로운 선택지의 변경 요건 따위와는 도통 무관히 어차피 끝끝내 한 획으로 한데 고스란히 동등 일치 반영 도출되기 마련입니다.\n\nHowever, the coefficients and their $p$-values do depend on the choice of dummy variable coding.\n하지만 정작 그들 자체 모수 계수 및 그 세부 통계 산출물 지표로서의 $p$-값 단면 수치는 전적으로 이런 식의 더미 변수 인코딩 선택 방식 기호 양태에 매우 지대한 수준으로 밀접 의존합니다.\n\nRather than rely on the individual coefficients, we can use an _F_-test to test $H_0 : \\beta_1 = \\beta_2 = 0$; this does not depend on the coding.\n그래서 이런 연휴로 개별적인 각각의 단독 계수만을 무리 주먹구구식 치우쳐 맹신 의존 판단하기보다는, 우리는 그보단 $H_0 : \\beta_1 = \\beta_2 = 0$ 이라 세운 귀무가설의 검증 목적 하에 훨씬 범주상 인코딩 그 차이 양식 방식과는 절대 결코 무관히 독자 노선을 취하는 기지인 _F_-검정(_F_-test) 을 도구 삼아 널리 응용 사용해 볼 수 있습니다.\n\nThis _F_-test has a $p$-value of $0.96$, indicating that we cannot reject the null hypothesis that there is no relationship between `balance` and `region`.\n이처럼 투영된 이번 _F_-검정 결과가 안겨준 총체적인 $p$-값은 매우 큰 치수인 $0.96$ 수준에 달하며, 이 수치는 우리로 하여금 차마 `balance` 요인과 `region` 두 요인 항목 그 사이에 일체의 구조적 상호 연관 관계 자체가 아예 결여돼 있다 공표하는 막막한 귀무가설 명제를 차마 과감히 기각 내팽개치지는 못할 거란 막강한 통계상 불문율을 한시 지름 지적해 가리키고 있습니다.",
    
    "Using this dummy variable approach presents no difficulties when incorporating both quantitative and qualitative predictors. For example, to regress `balance` on both a quantitative variable such as `income` and a qualitative variable such as `student` , we must simply create a dummy variable for `student` and then fit a multiple regression model using `income` and the dummy variable as predictors for credit card balance.":
    "Using this dummy variable approach presents no difficulties when incorporating both quantitative and qualitative predictors.\n결과적으로 보건대, 이런 류의 더미 변수 채택 접근법 요소를 가미 활용 구사하는 작업 행위 자체는 여타 지성적 정량 형태의 예측 요인과 또 여타의 단면인 다른 한 축 정성적 속성의 예측 변수, 즉 서로 무척 판이하게 이질적인 양단 체계 둘을 교묘히 배합 상호 통합 절차 도모를 진행 구상하는 와중에서도 그리 딱히 애로 사항이나 어려움이란 문제 장애를 전혀 발현 야기시키지 않습니다.\n\nFor example, to regress `balance` on both a quantitative variable such as `income` and a qualitative variable such as `student`, we must simply create a dummy variable for `student` and then fit a multiple regression model using `income` and the dummy variable as predictors for credit card balance.\n가령 그 한 예로, 정량 측정 단위 성향을 지닌 특정 `income` 물량 요소와 성격 측면이 전혀 대조되는 특수 정성 변수인 그 무어랄 것 없는 여타 요소 계열 `student` 분류 매개, 이들 둘 모두의 복합 쌍둥이 양대 자격 축을 구심 기반 기점으로 삼아 타깃 관할 지표 `balance` 요소가 걸친 방향성 각도로 한껏 기울여 통계 회귀 시키려 할 적엔, 그저 단순히 우리 쪽에서 우선 선 조치상 애당초 일찌감치 특정 `student` 파트 부분을 위해 무던히 더미 변수 틀 단면부터 재차 가볍게 가미 축조 조형시켜낸 뒤, 뒤이어 저마다 신용카드 실잔고 분별 예측 대상 후보 선상 표본 자격을 등에 업은 각 `income` 및 더미 변수 두 파트를 함께 써 다중 회귀 모델 모임 굿판에 제법 그럴싸하게 기계적 적합 투사시켜버리기만 하면 그 모든 수순 작업이 온전히 종결됩니다.",
    
    "There are many different ways of coding qualitative variables besides the dummy variable approach taken here. All of these approaches lead to equivalent model fits, but the coefficients are different and have different interpretations, and are designed to measure particular _contrasts_ . This topic contrast is beyond the scope of the book.":
    "There are many different ways of coding qualitative variables besides the dummy variable approach taken here.\n지금 당장 여기 단락서 우리 앞선 방식 기로상 쭉 전취 채택해 전개 진행했던 더미 변용 관련 인코딩 축조 접근 수법 요령안 이외에도 여럿 타 부가 형태의 무수한 세부 인코딩 부호 적용 수립 전개형 접근법 방식이 무성히 참 다채롭고 방대하게 더 많이 마련되어 있습니다.\n\nAll of these approaches lead to equivalent model fits, but the coefficients are different and have different interpretations, and are designed to measure particular _contrasts_.\n허나 이 무수히 다른 형국 접근 갈래 기선 체재 방식들은 하나같이 매양 기저 결론 산출 관점에선 최종 종착지에 동등한 유사 수준 적합 모형 궤적 치수를 똑같이 보란 듯 야기 인도해 내려줄 뿐, 정작 개별 계수만큼은 외관 속성상 완전히 판이 다른 상이한 체제를 시현 잉태 야기하며 덩달아 도무지 닮지 않은 숱한 해석 논쟁 거리를 불러일으키곤 할 뿐더러 실은 그런 다수 관습적 행위 방식 전부가 다름 아닌 모종 수준 일각 단위 체계상 다소 여유 특이한 성현 기반 부문 관할 특정 _대조군(contrasts)_ 요인 구도를 예의 실측 계량 타점 삼기 위한 특정 복적 설계를 띠곤 합니다.\n\nThis topic is beyond the scope of the book.\n물론 이 특유 부문의 대조 관련 세분화 주제 이슈 요소는 당초 본 서적 교재가 본디 목표 타협 기반 기조로 설정했던 다루기 지정 허용 주제 범위 수준 한계 척도를 한참 훌쩍 벗어나 넘어선 지대이므로 그 선망 도를 넘기게 됩니다."
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("done")
