import sys
import re

file_path = r"d:\site\jinydev\Statistical\src\book\c03\3_7_exercises\3_7_2_applied\index.md"
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    r"# _Applied_": r"""# _Applied_ 
# 응용 문제""",

    r"8. This question involves the use of simple linear regression on the `Auto` data set.":
    r"""8. This question involves the use of simple linear regression on the `Auto` data set.
8. 본 문항은 `Auto`(자동차) 데이터 세트 지표판을 무대로 삼아 단순 1차 선형 회귀 모의 연산을 기용 실습(involves the use of)해 보는 체제입니다.""",

    r"   - (a) Use the `sm.OLS()` function to perform a simple linear regression with `mpg` as the response and `horsepower` as the predictor. Use the `summarize()` function to print the results. Comment on the output. For example:":
    r"""   - (a) Use the `sm.OLS()` function to perform a simple linear regression with `mpg` as the response and `horsepower` as the predictor. Use the `summarize()` function to print the results. Comment on the output. For example:
   - (a) 본 교재망의 `sm.OLS()` 함수를 차출 사용해, 응답 결괏값으로는 `mpg`(연비) 지수를 두고 입력 예측축으로는 `horsepower`(마력) 변수를 기입 배정해 아주 단순한 형태의 선형 회귀 지표를 도출 단행 연산(perform)해 보십시오. 나아가 `summarize()` 함수를 동원 구동해 그 도출된 결과값을 화면에 출력 배포(print)해 내십시오. 도출된 산입 출력물 양상을 보고 제반 분석 논평(Comment)을 덧붙이십시오. 예를 들자면(For example):""",

    r"      - i. Is there a relationship between the predictor and the response?":
    r"""      - i. Is there a relationship between the predictor and the response?
      - i. 이 입력 예측 변수(predictor) 성분과 추정 응답 결괏값 사이에는 본질적으로 어떠한 모종 통계적 연관 역학 관계(relationship)망이 확연히 도사려 존재합니까?""",

    r"      - ii. How strong is the relationship between the predictor and the response?":
    r"""      - ii. How strong is the relationship between the predictor and the response?
      - ii. 만약 그 예측 변수와 응답 결괏값 진영 사이의 관계 역학이 존재한다면, 대체 어느 수위 징후 정도로 파급이 막강하며 그 위상이 강력 연루(strong) 됩니까?""",

    r"      - iii. Is the relationship between the predictor and the response positive or negative?":
    r"""      - iii. Is the relationship between the predictor and the response positive or negative?
      - iii. 이 입력 예측 변수와 응답 추정 결괏값 체제 사이의 도출 관계축망은 양(+)방향 수순 편향 곡선(positive)을 띠었습니까, 아님 상반된 음(-)방향 마이너스 득세 위상(negative)입니까?""",

    r"      - iv. What is the predicted `mpg` associated with a `horsepower` of 98? What are the associated 95 % confidence and prediction intervals?":
    r"""      - iv. What is the predicted `mpg` associated with a `horsepower` of 98? What are the associated 95 % confidence and prediction intervals?
      - iv. 극단적으로 엔진 마력(`horsepower`) 수치가 98인 구동 자동차 여건과 얽혀 파생 결부(associated)되었을 요량일 땐, 이에 호응해 산출 예측(predicted)된 `mpg`(차량 연비) 예상 점수는 대체 과연 몇 지수입니까? 아울러 이때 동반 도출 결부 지향된 쌍절치 95% 산입 수준의 신뢰 구간 단위 선상(confidence intervals) 및 이에 맞물린 예측 구간(prediction intervals) 폭은 도대체 어디서부터 어디까지입니까?""",

    r"   - (b) Plot the response and the predictor in a new set of axes `ax` . Use the `ax.axline()` method or the `abline()` function defined in the lab to display the least squares regression line.":
    r"""   - (b) Plot the response and the predictor in a new set of axes `ax`. Use the `ax.axline()` method or the `abline()` function defined in the lab to display the least squares regression line.
   - (b) 파이썬 체제상 신규 조율 세팅된 한 벌의 `ax` 구성 축(axes) 덩어리 지면 위로 이들 응답 결과치 차축과 예측 변수 도달축을 엇갈려 고스란히 띄워 차트 다이어그램으로 점철 그려(Plot) 보십시오. 앞선 실습 학습 지면 국면에서 정의 파악 논지(defined)됐던 바대로 `ax.axline()` 메서드 혹은 `abline()` 구동 함수를 고의 차용해 이 지면 점도 위로 거시 최소 제곱 최적합 회귀선 궤도 차축(least squares regression line)마저 번듯 시사 띄워 표기(display)해 얹으십시오.""",

    r"   - (c) Produce some of diagnostic plots of the least squares regression fit as described in the lab. Comment on any problems you see with the fit.":
    r"""   - (c) Produce some of diagnostic plots of the least squares regression fit as described in the lab. Comment on any problems you see with the fit.
   - (c) 숱한 앞선 실습 교재 내역에서 줄곧 장황히 서술 설파(described) 시사되었던 것처럼 최소 제곱 적합 귀결 지표에 얽힌 일련의 몇몇 다발성 진단 플롯 시각 점진 분석 시야도(diagnostic plots)들을 추가 연산 생산 도출(Produce)해 내십시오. 이 시차 적합 지수상 도출 망조 결과에서 당신의 혜안 눈으로 여지없이 여실히 파악 도출되는 온갖 크고 작은 여사 문제 편차 징후 요건 한계점(problems)들에 대해 소견 코멘트 논평(Comment)을 기입 달아 보십시오.""",

    r"9. This question involves the use of multiple linear regression on the `Auto` data set.":
    r"""9. This question involves the use of multiple linear regression on the `Auto` data set.
9. 이 문제 문항은 여태 앞서 소개된 `Auto`(자동차) 정규 데이터 세트 체제에다 대놓고 한결 복잡 다단한 다중 선형 회귀(multiple linear regression) 연산 모형 기조망을 교차 동원 기용해(involves the use of) 보는 징후 여정에 대해 가리킵니다.""",

    r"   - (a) Produce a scatterplot matrix which includes all of the variables in the data set.":
    r"""   - (a) Produce a scatterplot matrix which includes all of the variables in the data set.
   - (a) 해당 도출 데이터 세트 진영 도판 안에 파생 거주 잠복 속해 기용된 모든 전체 부문 통괄 속성 지표 변수 단위망(all of the variables)들을 단 한 개도 아낌없이 다 일렬 묶어 포함 통괄 병합시킨 대대적 거시 산점도 행렬 다이어그램(scatterplot matrix) 한 판을 낱낱이 도출 구축 생산(Produce)해 내십시오.""",

    r"   - (b) Compute the matrix of correlations between the variables using the `DataFrame.corr()` method.":
    r"""   - (b) Compute the matrix of correlations between the variables using the `DataFrame.corr()` method.
   - (b) 파이썬 체제 파생 도달 `DataFrame.corr()` 메서드 덩어리를 차용 기용(using)하여 뭇 포괄 변수들 무리 쌍들 상호 어깨 간에 도사려 맺어진 전방위 제반 거시 상관관계 수위표 행렬 성과 단위망(matrix of correlations)을 수술 교차 연산 산출 도달 계산(Compute)해 내십시오.""",

    r"`\.corr\(\)` \n\n": r"",

    r"- (c) Use the `sm.OLS()` function to perform a multiple linear regression with `mpg` as the response and all other variables except `name` as the predictors. Use the `summarize()` function to print the results. Comment on the output. For instance:":
    r"""   - (c) Use the `sm.OLS()` function to perform a multiple linear regression with `mpg` as the response and all other variables except `name` as the predictors. Use the `summarize()` function to print the results. Comment on the output. For instance:
   - (c) `sm.OLS()` 통계 함수 무리를 차출 호출(Use)하여 응답 목표 결과 조준치(response) 단엔 `mpg`(연비)를 위시해 못 박아 세워 두고, 기저 뭇 예측 요건 투입망엔 오직 차종 라벨인 `name`(이름) 변수 딱 이 녀석 하나만 거세 추방 제외(except)시킨 채 남은 여타 모든 뭇 수단 변수들을 일괄 파문 기용 투입 접목하여 거시 다중 다변 선형 회귀 단행 연산 분석(perform a multiple linear regression) 과정을 속 시원히 돌려 보십시오. 이어 `summarize()` 함수 도구를 부수적으로 이용 호출 기용해 해당 결과 망조 출력을 뿌려 띄우십시오. 다 도출 반환된 거시 출력물 양상(output)에 덧대 제반 본인 소견 논평(Comment) 코멘트를 달아 엮어 보십시오. 예컨대(For instance):""",

    r"   - i. Is there a relationship between the predictors and the response? Use the `anova_lm()` function from `statsmodels` to answer this question.":
    r"""      - i. Is there a relationship between the predictors and the response? Use the `anova_lm()` function from `statsmodels` to answer this question.
      - i. 일련의 저 다양한 기저 예측 변수(predictors)들 여건과 목표 응답 추정 도출 결괏값망 사이에는 본질적으로 어떠한 모종 역학 지표적 연관 관계 선로 수위(relationship)가 여실히 암초 도사려 존속 존재함이 입증됩니까? 이 의문 사안 질문지에 화답 방증 답변 지표 결론 도달(answer)을 이끌어 구축하고자 유독 `statsmodels` 파이썬 패키지 내부 `anova_lm()` 함수 구동 도구망을 엮어 차용 기용 응용(Use)해 보십시오.""",

    r"130 3. Linear Regression \n\n": r"",

    r"      - ii. Which predictors appear to have a statistically significant relationship to the response?":
    r"""      - ii. Which predictors appear to have a statistically significant relationship to the response?
      - ii. 그렇다면 도출 투입 연산된 일련의 저 예측 변수 무리들 중구난방 성분들 가짓수 중 과연 딱 집어 대체 어떤 부류 요건 지표 싹수 이면 항목(Which predictors)들이 궁극 도달 응답치와 통계적 제반 유의미도(statistically significant)가 철저히 짙은 결부 연루 궤도 관계성(relationship)을 띤 위상 궤도로 우뚝 가늠 발현 귀결된 걸로 식별 기조 파악(appear to)됩니까?""",

    r"      - iii. What does the coefficient for the `year` variable suggest?":
    r"""      - iii. What does the coefficient for the `year` variable suggest?
      - iii. 동반 적합 파생 연산된 결과 출력 지표 내역에서 저 차량 연식 `year` 기조 조달 변수에 한해 산입 토핑 달라붙은 파생 고유 산출 회귀 계수(coefficient) 수치는 우리에게 다소간 결국 궁극적으로 무엇(What)을 시사 암시 넌지시 증거 제의 주장 어필(suggest)해 주고 있을까요?""",

    r"   - (d) Produce some of diagnostic plots of the linear regression fit as described in the lab. Comment on any problems you see with the fit. Do the residual plots suggest any unusually large outliers? Does the leverage plot identify any observations with unusually high leverage?":
    r"""   - (d) Produce some of diagnostic plots of the linear regression fit as described in the lab. Comment on any problems you see with the fit. Do the residual plots suggest any unusually large outliers? Does the leverage plot identify any observations with unusually high leverage?
   - (d) 앞서 본문 상부 실습(lab) 단면 파트에서 줄곧 지면 할애해 거시 상기 서술 논지 일괄(described)됐던 처방대로 기저 선형 회귀 적합(linear regression fit) 도출 도달망에 수반된 일련 다발성 진단 플롯(diagnostic plots)군 그림 도판 다이어그램 몇 점을 추가 조준 돌려 생산 산출(Produce)해 매듭지어 보십시오. 이번 산입 도출 적합 지수상 기조에서 귀하의 안목망에 직결 파악 들이찬 여느 온갖 편차 불협 증세 문젯거리 한계 결여 요건(problems)들에 대해 소견 차원의 논평(Comment)을 제의 부연 달아 주십시오. 파생 생산된 이들 잔차(residual) 도표 시각 화면 구조도 플롯망의 궤적 군상은 행여나 여사 이례적으로 단대히 비대증폭 막대히 기막히게 큰 위상을 띤 여느 특이점(이상치, outliers) 징후 이탈 기표군을 명징히 시사 암시 발현 지목 암시(suggest)해 주고 남음이 있습니까? 아울러 파생 레버리지 검토 플롯(leverage plot) 구도는 혹시나 특출나게 드높은 치수의 작용 영향 지렛대 관측 맹위 레버리지 기운(unusually high leverage)을 도무지 통제 불능 가공스레 머금고 뽐내는 모조 둔갑 변질 관측 결과(observations) 하나하나를 예의 낱낱이 색출 식별 가려 파악 지목 차출 도출(identify)해 잡아내고 있습니까?""",

    r"   - (e) Fit some models with interactions as described in the lab. Do any interactions appear to be statistically significant?":
    r"""   - (e) Fit some models with interactions as described in the lab. Do any interactions appear to be statistically significant?
   - (e) 앞 상부 실습 시사(described in the lab) 항목에서 이미 거론 기용됐듯, 파생 변조 이탈 엇갈려 얽힌 통계 부합 상호 작용 지표(interactions) 항구 요소들을 이리저리 다소간 입맛 부문대로 추가 곁들여 산입 버무린 여느 파생 우회 변형 다중 신규 도출 모델(models) 형태들을 별도로 또 몇 개 전격 세워 구축 변조 적합(Fit) 연산 분석시켜 보십시오. 이처럼 숱한 무수 조합 가공 동원해 우겨넣어 곁들여 친 상호 작용 조합(interactions) 항 지수 무리 덩어리 시사 속 조각들 중, 단연 단 한 개 기조 항목일지언정 정녕컨대 통계적 수치상 제반 유의미성 궤도 전선을 단호히 구축 성립 관철한 우월(statistically significant) 지경에 우뚝 선 부합 싹수 결괏값 존재가 파악 출현 발굴 도달(appear to)된 바 확연히 도출 포착되었습니까?""",

    r"   - (f) Try a few different transformations of the variables, such as log( X ), _√X_ , X\[2\] . Comment on your findings.":
    r"""   - (f) Try a few different transformations of the variables, such as log( X ), _√X_ , X^2 . Comment on your findings.
   - (f) 여느 숱한 파생 지정 통괄 변수 항목들을 대상으로 가령 $\log(X)$ 로 치환하거나 아예 $\sqrt{X}$ 전격 혹은 $X^2$ 로 막 튀고 부스팅 배가시켜 버리는 일련의 다채 기기묘묘 다른 수리 이종 수치 변환 개조(different transformations) 기법 공식을 몇 번 가볍게 두루뭉술 시도 기용 연산 적용 타진 구사 단행(Try)해 보십시오. 그리고 이 과정 단면망에서 갓 찾아 발견 파악 도출해 낸 귀하 무수 특수 지표 성과 발견물 전향 발견 결괏값(findings) 궤적 양상군들에 두루 제반 논평 소견 코멘트(Comment)를 일괄 제동 편입 작성 나래 달아 주십시오.""",

    r"10. This question should be answered using the `Carseats` data set.":
    r"""10. This question should be answered using the `Carseats` data set.
10. 본 묻고 답하기 10번 국면의 제반 다변 문항 질의 사항들에 대해선 모름지기 일괄 필연 당번 이 전술 정규 `Carseats`(유아 카시트) 시판 매물 도달 표본 데이터 세트 지표군만을 오직 단일 활용 적용 차출 기용해(using) 풀이 산입 후 답변 제시 연루 귀결 응답안(answered)을 성사 타진 도출 내야만 합니다.""",

    r"   - (a) Fit a multiple regression model to predict `Sales` using `Price` , `Urban` , and `US` .":
    r"""   - (a) Fit a multiple regression model to predict `Sales` using `Price` , `Urban` , and `US` .
   - (a) 시판 단가액(`Price`), 관할 매장지 입지 도심권 여부(`Urban`), 아울러 매장 국적 미국 본토 소재권 결여(`US`) 딱 세 갈래 부문 지수들만을 차출 기용 투입 접목(using)해 이 연합력으로 목표 타깃 아동용 시트 판매량 수치 지수 실적고(`Sales`)를 점쳐 예측 추정 유추(predict)해 단행토록 이끄는 일개 무리 통합 다중 회귀 모델(multiple regression model) 연산 잣대 하나를 오롯이 세워 도출 분석 연루 적합(Fit) 구동시켜 보십시오.""",

    r"   - (b) Provide an interpretation of each coefficient in the model. Be careful—some of the variables in the model are qualitative!":
    r"""   - (b) Provide an interpretation of each coefficient in the model. Be careful—some of the variables in the model are qualitative!
   - (b) 산입 구축해 적립 세운 이 모델의 구동 잣대 지표 분석표 상에 등장한 각각 각 부문 개별 파생 고유 회귀 계수(coefficient) 조각 지수들 전반 일체마다 도대체 이들이 무얼 대변 시사하는지 그 통찰력 돋보이게끔 한 줄 한 줄 촘촘 상세 세세 통계 분석 해석안 요해 지표(interpretation)를 제안 서술 부연 제공(Provide)해 표기해 보십시오. 단, 행여나 이때 여하 불문 돌다리도 두드려 짚고 넘어가 각별 요주의 기조 십분 유념 경계 조심(Be careful)하십시오—왜냐하면 이 애처 구동 세워 모델에 당장 기용 투입 동원 산입 도달된 부문 제반 몇몇 다수 통제 변수 요소 가지군 중엔 응당 이른바 정성적 비수치 위주 지표인 부류 특성(qualitative)의 얄궂은 데이터군이 이미 혼조 수반 섞여 있기 마련인 때문입니다!""",

    r"   - (c) Write out the model in equation form, being careful to handle the qualitative variables properly.":
    r"""   - (c) Write out the model in equation form, being careful to handle the qualitative variables properly.
   - (c) 바로 전 앞서 그간 도달 산출 적합 도출망으로 세워 낸 이 다중 회귀 모델 기조 식단을 모름지기 단순 무식 완전 수리 전용 방정식 외형 양식 체제 등식 꼴 구조(in equation form)로 낱낱이 다 일렬 가다듬어 늘어 세워 지면에 고스란히 옮겨 적어 기입 표기 표출(Write out)해 산술해 보이십시오. 단지 여기 거시 기조 조건서도 방금 전 위 질의처럼 해당 이질적 카테고리 질적 성격(qualitative variables)을 띤 무리 정성 변수 지표 파편들에 한정해선 행여 구조적 충돌 수학 혼동 곡해를 피해 제대로 엄밀 부합 단절 정교 알맞게끔 그 취합 가치 단위를 제구실 온전 정확히 다듬어 처리 조작(handle properly)하도록 매사 십분 만사 꼼꼼 경계 각별 심혈 고도 경계(being careful) 기울여 조치해야 합니다.""",

    r"   - (d) For which of the predictors can you reject the null hypothesis $H_0$ : $\beta_j$ = 0?":
    r"""   - (d) For which of the predictors can you reject the null hypothesis $H_0$ : $\beta_j$ = 0?
   - (d) 당장 일괄 쏟아 부어 넣은 일련의 뭇 입력 파생 예측 변수 항목 무리 조각(predictors)들 중대 단연 과연 딱 집어 어느 요소 속성 특정 항목 갈래들 조각(For which)에 한해 국한해서만, 필경 귀하는 "이들의 회귀 지수 위상값은 사실상 실체 통계상 전무 쓸모 없다"라고 역설 외친 바 저 기저 무기력 허무 귀무 가설(null hypothesis, $H_0 : \beta_j = 0$)의 주창 논리선 결박 굴레 명제망을 온전히 말끔 후미 통쾌 시원히 배격 묵살 일축 기각 반박 물리쳐 파기(reject)시켜 줄 강력 타진 권리 기조 명분을 부여받을 수 있는 걸까요?""",

    r"   - (e) On the basis of your response to the previous question, fit a smaller model that only uses the predictors for which there is evidence of association with the outcome.":
    r"""   - (e) On the basis of your response to the previous question, fit a smaller model that only uses the predictors for which there is evidence of association with the outcome.
   - (e) 바로 위 전단계 질의 조항(previous question) 과정 맥락에서 귀하가 속 달여 이끌어 제시 답변 파악 방증(your response)해 주창해낸 기조 도출 판별 기준과 단서 결론을 오롯이 굳건한 논지 바탕 신뢰 기조(On the basis of) 핵심 구심점으로 단단히 뿌리 내려 삼아, 오직 그 궁극 최종 타깃 결과 도출 결론 이탈 방증 지수(outcome)와 도무지 깊이 한데 얽히고 통계 결부 시야 도달 직결 유의성(association) 관련 지표 방증 단서 기동 시사 개연 증거 척추 흔적(evidence)이 강렬 짙게 입증 감지된 살아남은 일부 파생 위상 예측 덩어리 변수 조각들 부류 국한 한정 부문(predictors)만을 간소 가뿐 수위로 모조리 단지 오직 고스란히 취사선택 발췌 기용(only uses)해 이로써 한 차원 그 외형 구성 부피가 전보다 한 치 더 다소 작고 아담 날렵 슬림 간소해진 파생 축소 신규 다변 축약 모델(smaller model) 잣대판을 번듯 후행 재차 갱신 도달 적합(fit)시켜 보십시오.""",

    r"   - (f) How well do the models in (a) and (e) fit the data?":
    r"""   - (f) How well do the models in (a) and (e) fit the data?
   - (f) 도출 연산 과정 상 맨 처음 원론 단계 (a)번 조항 파국 국면에서 무턱 일괄 파생 도달 세워낸 날것 거시 방대 다중 기본 회귀 모형과 뒤이어 후 차원 방금 최신판 슬림 조향된 막바지 부문 (e)번 국면 수위상의 지표 여건 한정 축소 파생 모형 잣대망(models), 이들 두 극단 시기 시점 파생 위상의 전 후 모델군들은 각자 자신에 할당 주어진 본연 공통 데이터 판형 기반 세트상에 맞대 밀착 척도(fit the data) 진전 도달해 봤더니 그 데이터 굴면 일선 추정 실측 편차 상으론 둘 다 도대체 속 시들치 과연 얼만큼 고차원 정교 돋보일 만치 오차율 없이 두루 적합하고(How well... fit) 정녕 얼마만큼 유달리 무난 수려 잘들 들어맞고 밀착 일치합디까?""",

    r"   - (g) Using the model from (e), obtain 95 % confidence intervals for the coefficient\(s\).":
    r"""   - (g) Using the model from (e), obtain 95 % confidence intervals for the coefficient(s).
   - (g) 앞선 항목 과정 궤도 (e)번 도출상 부문 조항 선상에서 이미 군더더기 처내고 정렬 도출 수세 적합해 확립 확고 다져진 저 간소 축약 정예 특선 슬림 축소 신규 구축 파생 모델 뼈대 지표 잣대 기동 모형판 구도 위상(model from (e))을 전적으로 유효 오롯 적용 기용 신뢰 차출 의존 기저 활용(Using)하여, 당면 동반 모델 내 속해 가동 연출된 개별 전체 각각 여러 연루 파생 고유 회귀 지수 부문별 계수(coefficient(s)) 성분 가지들 일괄 전 대상 무리마다 정조준 쌍심지 도달 기준치 95% 산입 확률 수위 포섭 위상의 도출 신뢰 구간 쌍절 통계 장치(95 % confidence intervals)를 넉살 가파르게 모두 계산 기진 수려 도단 파견 산출 도파 구득(obtain) 획득해 도출해 내십시오.""",

    r"   - (h) Is there evidence of outliers or high leverage observations in the model from (e)?":
    r"""   - (h) Is there evidence of outliers or high leverage observations in the model from (e)?
   - (h) 또 줄곧 앞 기조 연계 단계 부문 저 (e)번 거시 상황선에서 확고부동 매듭 쇄신 산출되어 건져져 전위 기용 도출 단행 적합 확립된 ওই 최신 특수 한정 정예 축소판 변조 모형망 체제 지평(in the model from (e)) 수위 내부 국면에선, 당장 애먼 곳 판별 시야 거시 분석상으로 저만치 툭 유별 동떨 어진 이색 일탈 파괴 이상 궤도 유별 관측치 위상체(outliers) 징후군 개입 존재 여부 또는 무모 막대 기저 과잉 가도 기형적 유도 자성 포진 높은 상위 엄청 유달 초과 과열된 다중 통제 위력 영향 이반 압력 강요 위세의 레버리지 둔갑 개별 기이 관측 포획물(high leverage observations) 성분 지표 개체 조각 파편 등 파생 잔차 이상 이변 발생 요건 틈새의 실질 맹위 실효적 연루 유무 개연 의심 방증 가능 전선(evidence)들이 과연 어딘가엔 심층 기동 단서 적발 포착 시사 감지 도사려 산재해 잔존 존재 도출(Is there)됨이 판가름 확연 발견 납득 입증되기는 합니까?""",

    r"11. In this problem we will investigate the $t$-statistic for the null hypothesis $H_0$ : _β_ = 0 in simple linear regression without an intercept. To begin, we generate a predictor `x` and a response `y` as follows.":
    r"""11. In this problem we will investigate the $t$-statistic for the null hypothesis $H_0$ : $\beta = 0$ in simple linear regression without an intercept. To begin, we generate a predictor `x` and a response `y` as follows.
11. 자 이 대목 당면한 차례 문제 질의 구간(In this problem) 진영 수위에선 우린 우선 고의 기조로 절편 상수(intercept) 성분을 애초 쏙 들어내 전면 배제 생략 차단 누락시켜(without) 다분 작위 이색 조율 편향 통제 국면 구도로 이질적 단순 일개 단편 선형 1차 모델 회귀 분석(simple linear regression) 연루 파생 조치 산입을 단행해 버린 특별 국한 단면 기이 축소 조망 조건하에서의 전선 궤적망을 대상으로 삼아, 무릇 저 유명 통계 기조 "회귀 이 수식 변수엔 아무 효과 개입 지배 연루 편차가 도무지 하등 전무 위력 없다"라고 고집 주창하는 이른바 무위 공허 아무짝 무용론 헛심 기조 귀무 가설 허무 잣대 명제(the null hypothesis $H_0 : \beta = 0$)의 주장에 얽힌 고유 산입 단면 파생 판별 지수 $t$-통계량(t-statistic) 동반 수위 진척 향방 및 성쇠 진위를 샅샅이 집중 분해 추적 연루 고찰 조사 탐구(investigate) 분석해 파헤칠 요량입니다. 이런 탐구 실험 착수 가동을 제일 먼저 일단 단일 기치 도달 돌입 전격 시작 감행(To begin)해 보기 차원에서, 우리는 편의 선제 사전 하위 기입 코드 블록 산술 예시 배분 기재와 같이 이들 모형의 단순 근원 인자 예측 변수 축 도구망 항목 `x` 조각 지표와 이에 맞물려 상호 대응 도출 목표 파생값 대상 기조인 결괏값 대상 뭇 응답 성분 타깃 덩어리 `y` 체계 구조 요건을 다음 나열 기술 제시된 덧붙임 순차 과정 안내 방식 기조 연산 조작 구술 이행 체재와 같이 지렛대 일괄 임의 인위 랜덤 난수 산출 추출 파생 조달 생성 생산(generate) 처리 제조해 조치 구축할 것입니다.""",

    r"""rng=np.random.default_rng(1)
x=rng.normal(size=100)
y=2*x+rng.normal(size=100)""":
    r"""rng = np.random.default_rng(1)
x = rng.normal(size=100)
y = 2 * x + rng.normal(size=100)""",

    r"- (a) Perform a simple linear regression of `y` onto `x` , _without_ an intercept. Report the coefficient estimate \hat{\beta} , the standard error of this coefficient estimate, and the $t$-statistic and $p$-value associated with the null hypothesis $H_0$ : _β_ = 0. Comment on these results. (You can perform regression without an intercept using the keywords argument `intercept=False` to `ModelSpec()` .)":
    r"""   - (a) Perform a simple linear regression of `y` onto `x`, _without_ an intercept. Report the coefficient estimate $\hat{\beta}$, the standard error of this coefficient estimate, and the $t$-statistic and $p$-value associated with the null hypothesis $H_0: \beta = 0$. Comment on these results. (You can perform regression without an intercept using the keywords argument `intercept=False` to `ModelSpec()`.)
   - (a) 기저 타깃 응답 결괏값 `y` 부문 산입 성향 축을 온전히 또 다른 인자 투입 변수 기조 잣대축 `x` 도달 지표상에 대놓고 얹어 맞물려 결부 기용 단행시킴(onto parameter `x`)으로써 일개 순수 조달 1차 단면 단순 선형 회귀 모의 수위 조치(simple linear regression) 연산을 속 시원 단박에 기어코 강행 수행 구동 접목 타진 도출(Perform)해 내십시오, 단 이때 절대 명심 요주의 고도 엄수 조건 기조로 절편 상수 성분(an intercept) 파트는 단호 _배제 누락 생략(without)_ 한 이례적 축소 전제 결박 상태 위상 고의 차단 구도여야만 국한 달성 명심합시다. 그리 처리 구단 산입 조달 구동 단행 후 기어코 최종 도출된 속성별 각종 파생 결괏값 수위 덩어리, 즉 거시 전체 연루 산입 기울기 방향 회귀 계수의 산출 예측 도출 추정 획득 분량 지수값 성분 요체 지표인 $\hat{\beta}$ 수위와 더 달여 이 산출 예측 획득 추정된 당면 파견 적법 계수 치수 지향에 딸린 공속 수반 산입 오차 범위 확산 지표인 고유 수반 표준 오차 폭(standard error) 요인 치수, 거기에 곧장 이어 동시 파생 줄지은 무용론 기각 무기력 제의 공회전 입증 위상 주창 논지인 특정 제반 귀무 가설 허구 전선 잣대 명제($H_0: \beta = 0$)와의 심층 개입 연결 수반 상응 연루(associated with) 공속 지향된 파생 속성 잣대 수위 지표 판독 부문인 산입 $t$-통계량(t-statistic) 성분 점수치와 오롯이 이와 줄달여 병합 기용 발탁 판세 결정 중추 조율 산정 잣대 수위치 끄트머리 방증 도달 파생 환산 유의 결말 점수인 산입 $p$-값(p-value) 성과 수위를 모두 낱낱이 파악 수집해 하나하나 나열 보고 제출(Report)해 기입 올리십시오. 이 모든 추출 수반 도달 관찰 산출 결과 동향 징후 귀결 궤도 도출 수위치들 양상 파생(these results) 전반 국면에 대해 면밀 진단 분석 제의 소견 논지 코멘트 논평(Comment)을 작성 나래 달아 이끄십시오. (부연 팁 상기 요령 단서 안내: 당신 독자 실습 진행 연산자는 도달 모델 수위 설계 부문 조작 설정 잣대 기저 통제 관할 함수 도구인 `ModelSpec()` 단편 차출 부문 입력란 지향 호출 영역 안에 고도로 명문 키워드 표기 전용 인자 문구 쐐기 단서 파편인 `intercept=False` 제재 명문을 살짝 얹어 삽입 통과 차용(using the keywords argument)해 들이밀면, 능히 애써 번번 무리 구동 수수 않고 그저 손쉽고도 너끈히 별 탈 어김 제동 없이 이른바 일체의 뻔한 상수 제반 절편 개입 성분 지표가 송두리째 쏙 빠져 탈피 완전히 모조리 깔끔 제외 거세 절단 타파 생략 누락 결번(without an intercept)되어진 기이 희소 쇄신 특이 형태 국면 고의 제한 회귀 적합 산술 연산 도출 구동 단행 타진(perform regression)을 척척 일별 거뜬 거시 완수 이룩 성과해 낼(You can... 수행 도달) 수 능히 십분 거시 자명 보장 마련 입증 존재 가능합니다.)""",

    r"3.7 Exercises 131 \n\n": r"",

    r"- (b) Now perform a simple linear regression of `x` onto `y` without an intercept, and report the coefficient estimate, its standard error, and the corresponding $t$-statistic and $p$-values associated with the null hypothesis $H_0$ : _β_ = 0. Comment on these results.":
    r"""   - (b) Now perform a simple linear regression of `x` onto `y` without an intercept, and report the coefficient estimate, its standard error, and the corresponding $t$-statistic and $p$-values associated with the null hypothesis $H_0$ : $\beta = 0$. Comment on these results.
   - (b) 자아 여기까지 왔으면 이제부턴(Now) 살짝 판세를 역행 시점 치환 전개 스왑 전환 반전시켜, 역으로 기저 투입 예측 응답 변수 단면 지위 역할 잣대 방향축마저 스리슬쩍 반대 역방향 상반 축으로 바꾸어 이탈시켜 응답 타깃 결과 잣대 축 대상을 `y` 로부터 거꾸로 역 단안 응답 방향 추이 목푯값 축을 `x` 변수로 삼아 배정하고, 도통 전면 역 위상 지수 이면 예측 수단 지표 전술 변수를 종전 기저 입력 부문이었던 `x` 로부터 이번엔 외려 역 추적 이 위상 이례적 예전 결괏값 대상이던 단면 타깃 종속 응답 대상치였던 파생 조달 축 단위 결괏값 도출 파편 도구 표적 변수치 지수 체계인 `y` 수위 상 위로 기어코 뒤바꿔 엎어 얹어 대입 결부 적합(of `x` onto `y`) 구동 연산 분석시킨 단면 역순 파생 도달 시발 역방향 기조 산입 단순 1차 단편 일방 선형 편향 단도 회귀 분석 모형 구조 연산 단행 적합 시행 타진 산입 조달 구동(perform a simple linear regression) 단계를 다시 이행 수행 처리 완수 전개해 일별 보십시오, 물론 여기 이때도 전 과정 동반 단행 조건과 줄곧 변함 매한가지 동등 이례 구도 제한 조율 유지 관철 동일 국한 동일 제한 고의 통제 조치 부연 제약 강제 설정 부문으로서 당연지사 결론 거시 모형 설계 구축 기반 구조 맹위 식단 전선 내 절편 상수 배정 요건 성분 지수 파편 도입 배정 항목 만큼은 한사코 절대 통제 여실 없이 절대로 또다시 속 빈 강정 치외 일괄 결연 단절 통째로 영구 가차 배제 결여 박탈 완전 생략 누락 결번(without an intercept) 시켜버린 한정 조작 통제 수단 축소 진척 이면 설정 국면 위축 틀 제약 상태 시야 전제 조건 제한 한계 안에서만입니다. 그리 역 단행 회귀 궤수 징후 치수 도출 후 얻어낸 산출 파생 여건 결괏값 위상 궤도 산물 수위들, 이를테면 위상 역전 역 역대 회귀 계수 산출 파생 예측 도출 추정치 결과 추청 요체 성분 점수 크기 위상값 분량(\hat{\beta} 지표), 그 해당 구체 역순 계수 파생 수위 요인 치수치 이면에 수반 파생 오차 확산 결부 지향된 쌍절치 공속 기조 파생 산입 고유 자기 표준 확산 에러 오차폭 치수 지표 동향 수치(its standard error), 그리고 줄이어 한 묶음 일괄 대대 매한가지로 이전 귀무 단편 부질없음 효과 무력 상쇄 전면 부정 부재 허구 조달 주장 기치 모형 가동 무위 가설 제의 모용 허무 전선 주장 허수 명제(\({H_0} : {\beta = 0}\))의 제반 허무 전위 주창 기조 선로 명제 맥락과 맞물려 연관 파생 깊숙이 대응 결부 호흡 부합 공속 수반 연루(associated with) 지향 맞닿아 있는, 바로 그 상응 합치 적법해 대응 조치 부합 부응 부합된 동반 기인 특정 해당 관련 전담 결부 귀결 속성 개체인 파생 관련 상응 공조 적합 필연 특정 \(t\)-통계량 평가 진위 부과 구별 환산 조율 점수(the corresponding t-statistic) 요체 및 부차 파생 공속 동조 결여 상응 귀결 연합 진위 분별 제반 결판 판별 타진 의사 판결 수위 가늠 결정 이면 연루 지수값 부문을 맡아 타진 이끄는 최후 막바지 관문 파생 한계 공조 점수 수위 결괏값(\(p\)-values 지표 수위군) 등 거시 일련 전체 모든 제반 산입 결괏값 무더기 궤적 군상 덩어리들을 여실 구득 입수 수집해 남김 낱낱이 발췌 전면 보고 타진 산입 개진 제출(report) 단행해 보십시오. 그리고 도출 확인 산입 전개 조달된 이들 파생 모든 변차 기조 전환 국면 수위 궤적 성과물 양상 도출 관찰 환산 발견 제반 도출 이변 결괏값 여파 지수 파편(these results) 체제 국면 전반에 대해 면밀 주시 여실 비평 진단 진척 타진 가늠 고찰 깊은 소견 평단 주관 분석 평가 논조 덧글 코멘트 부연 소견 서술 기입 필단 논평(Comment) 흔적 자취를 마저 이면 속속 남겨 보태어 전개 이끄십시오.""",

    r"- (c) What is the relationship between the results obtained in (a) and (b)?":
    r"""   - (c) What is the relationship between the results obtained in (a) and (b)?
   - (c) 이리 돌고 돌아 방금 여차저차 윗선 전초 기조 궤도 전제 조건 (a) 단락 문항 진행 여정 코스 선상 무대 부문 내부에서 거시 수수 얻어 전격 달성 차출 입수 도출 취득 획득(obtained) 해낸 여력 제반 뭇 도출 궤도 속성 산물 관찰 결과 지수 통계 양상 산입 결괏값 무리 덩어리 지수군들(the results)과 그 후발 곧이어 반전 단안 파생 제 (b)번 관건 조항 지표 문항 진행 역방향 치환 국면 궤도 상의 거동 연루 부문 코스 여정을 통해 이면 재차 반대로 거꾸로 휙 획득 차출 도출 구득 요해 포획 성취 얻어(obtained) 산출 파생해 이면 쟁취해 가져온 또 다른 역위상 궤도 편차 전면 산입 양상 결괏값 지표 뭉치들(the results) 사이 간의 심층 조달 역학 궤도선상 내막 구도 구조적 상호 대비 굴절 얽힘 내재적 결부 수위 연루 공생 양상 역학 제반 표리 연결 결탁 편충 맞선 관계 위상 촌수 역학선 구도 연관 기조의 정체 끈(the relationship) 선은 도대체 결국 궁극 무엇이라고(What is) 어떻게 결론지어 한마디 거시 무리 서술 지칭 특징 정의 규정 요약 거론 정의해 맺을 명제 단언 결론 가늠할 수나 있겠습니까?""",

    r"- (d) For the regression of Y onto X without an intercept, the _t_ - statistic for $H_0$ : _β_ = 0 takes the form _β/_[ˆ] SE( \hat{\beta} ), where \hat{\beta} is given by (3.38), and where":
    r"""   - (d) For the regression of $Y$ onto $X$ without an intercept, the $t$-statistic for $H_0 : \beta = 0$ takes the form $\hat{\beta} / \text{SE}(\hat{\beta})$, where $\hat{\beta}$ is given by (3.38), and where
   - (d) 거시 보편 기조상 전면 통제 수위 발동 여건 하에 절편 수치 고유 가동 조달 변수 변조 상수항 자체를 아예 통째 거세 송두리 배제 탈락 거절 결여 누락 누절 삭감 배제시킨 채 도달 제한 압수 누락 배제 생략 삭제(without an intercept) 무방 조작 시켜 놓은 인위 특수 제단 조작 한정 압박 이면 변수 제약 국면 굴레 조건 환경 세팅 조달 판 위 속에서, 타깃 결괏값 응답 지표 대상 변수인 이른바 거시 종속 반응 $Y$ 진영 부문 타깃 응답 치수 지수 성향 기조를 거꾸로 입력 기작 예측 수단 인자 발탁 단면 기조 도구 잣대축 $X$ 예측자 축 위로 편입 동반 안착 부합 탑재 매듭 대입 안치 투입(of $Y$ onto $X$) 얹어 결부 돌려 버리는 구조식 방식 회귀 선형 무리 구동 적합 연루 분석 통계 단행 연산 기법 조달 파생 도출 전개 가동(regression) 궤수 행로 궤도 방식에 한해(For), 저 유명한 효과 없음 소멸 무력 허상 존재 무위 부정 단절 체제 귀무 가동 명제 모의 허무 제의 기치 가설 명제인 $H_0 : \beta = 0$ 기조 진위 주장 주창 판별 연루 분별 기각 수용 검정 시험 국면 타진 조항에 깊숙 연루 파고 수반 부응 상응 필연 도달 파생 귀결 부합 대응 결부 맞물려(for) 파견 제공 도달 조달 동조 배정 형성 배분 차출 맺어지는 이른바 특정 결판 결정 도달의 고유 산입 해당 특정 파생 $t$-통계량(the t-statistic) 지표 환산 점수 성향 수치 공식 분량값 자체는 모종의 통계 수학 증명 이론 역학 구조 원리에 의거 으레 필시 다음 후술 나열 서술 기술된 대수 방정식 통계 모형 비례 공식 외형 단면 형식의 외피 겉옷 구조 형태 양상 구도 진영의 생김새 껍데기 꼴 틀(the form)을 전형 불문가지 전면적으로 흔쾌 으레 무조건적 어김 당연 무진 단박 다분 여실 기꺼이 억척 취득 수용 고착 취해 띠고 지니며 귀결 도달 성립 안착 귀환 발생 묘사(takes)되게 마련 전개 진행됩니다. 바로 이 무리 다변 일련 도출 산물 결괏값 궤도식 환산 수위식 계산 파생 분수 조율 비례 구조 공식 체제 비율 수식 꼴이란 $\hat{\beta} / \text{SE}(\hat{\beta})$ 이 조촐한 단순 무지 연산 단면 식 형태 모형입니다. 여기서(where) 분자 꼭대기 자리 진영을 차지 거머쥔 이 요점 예측 도달 지표 추정 잣대 수위 계수 측량 $\hat{\beta}$ 분량 성분 요체 지표 값 파편 치수 조각 자체는 이미 그 수록 조달 형성 배경이 일말의 교재 거론 본문 앞자락 상단 중추 핵심 역학 도출 기술 부문 편제 (3.38) 제재 조율 증명 공인 수석 수식에 의해 미리 이면 타진 발탁 증명 정의 귀결 결정 전향 제공 조달 확정 확립 규명 도출 증여 지표(given by)된 바 고스란히 주어진 상태 위상이며, 그리고 덧붙여 그와 연계 맞물린 분모 수위(and where) 요체 지수 도달의 산경 파행 위상 오차폭 변조 조달치 궤적값은:""",

    r"**==> picture \[133 x 31\] intentionally omitted <==**":
    r"""$$ \text{SE}(\hat{\beta}) = \sqrt{ \frac{\sum_{i=1}^{n} (y_i - x_i \hat{\beta})^2}{(n-1) \sum_{i=1}^{n} x_i^2} } $$""",

    r"\(These formulas are slightly different from those given in Sections 3.1.1 and 3.1.2, since here we are performing regression without an intercept.\) Show algebraically, and confirm numerically in `R` , that the $t$-statistic can be written as":
    r"""(These formulas are slightly different from those given in Sections 3.1.1 and 3.1.2, since here we are performing regression without an intercept.) Show algebraically, and confirm numerically in `Python`, that the $t$-statistic can be written as
(단, 여기서 노파심에 부연 환기 고지 지적 당부 참작 첨언하자면 이들 방금 거론 들이민 하위 위상 제시 조달 단면 궤적 산출 이 특수 파생 도달 방정식 나열 공식 연산 구조 체계 수식(These formulas)들 면면 자체는, 일찍이 앞선 본 서적 교재 문헌 앞전 챕터 파트 구획 제 3.1.1절 및 연이어 뒷 따르던 3.1.2절 부문 구간 선상 도달 수위 본문 등 지점에서 애먼 제시 파견 도출 공시 수록 기재 발탁 기술 열거 안내 주입 공여 배포 공개 구비 제공 소개(given in)되었던 그들 원래 기존 일련 통상 거시 보편 주류 여느 기층 오리지널 통계 회귀 지표 기본형 도출 구조 연산 기본 수식 공식 산출 계산 궤적 옹호 공식 덩어리들 무리 무더기(those)들과 비교 매칭 참조 대응 유추 대조 감별 견주어 봤을 시 상당히 여러모로 은근 슬쩍 미세하게 모종 부문 일치 어그러져 어긋 이탈 편차 진전 변조 변형 부분 약간 상이 꽤나 다소 조금 미묘 확연 눈치 차이 불일치 편차 소폭 조작 변경 다르게 빗겨 앙달 동떨 별반 이질적 다르게끔 소폭 미미(slightly different from) 짜여 기형 설정 이반 왜곡 표기된 셈 치수 양상 격인 건데, 그 필연 본질 조작 이탈 사정 연유(since)는 다름 아니라 현재 이곳 당면 국면 문제 풀이 현황 현주소 특수 조작 시련 무대 판 위 현 지점 이 도달 구도 여건 국면 시야 위(here)에선 이미 우리가 애초 여건 기용 통제 설정 구심 잣대 기조 연산 발동 궤도를 통상 보편 이면 관례 원행 다르게 상수 절편 부문 성분을 아예 절대 거세 단호 누락 완전 배제 무단 절단 결여 배척 철저 생략 제외(without an intercept) 통제 이탈 시켜 버린 강제 특이 기이 제약 조건 조달 환경 상태하에서 국한 한정 편파 회귀 선형 무리 구동 도출 강행 연루 모형 연산 평가 실측 적합 가동 산입 분석 부문 통계 단행 강도 연산 조치 수행 모의 시행 기조를 고스란히 이끌 펼쳐 구동 수행 이어나가(we are performing regression)고 있었던 도출 원행 돌발 상황 사유 이유 까닭 단서 사실 배경 때문인 게야요.) 이 같은 대입 파악 정보 근거 공백 기조 사실 이면 지수 전선을 요약 자산 토대 무기 밑천 발판 근거 기저 잣대 통계 초석 원천 바탕(algebraically)으로 거듭 단단 삼아 묶어, 전방 도달 공용 파생 도달 무구 이 $t$-통계량(t-statistic) 구동 지수 부문 성립 치수 공식이 무던 수학 대수학(algebraically)적 원론 공식 수리 연쇄 이항 치환 방정식 조율 해체 기호 변환 조합 방식의 복합 수기 증명 도출 진전 논파 논증 입증 논리 기조 이면 산술 도출 수작업 대수 시야식(algebraically) 수리 연산 공식 연계 절차 과정으로도 보란 듯 이내 막힘 거침 무리 유려 여지없이 하단 이면 지면 구석 조달 여느 명시 표기 거론 안내 서술 기입된 바 바로 뒤 따르는 요런 신비 진전 모양 꼴 외피 껍데기 형식 공식 대형 구조 방식의 이채로운 요해 수식 모양 형태 구도 조달 양상으로 거뜬히 단박 재차 매끄럽 무방 탈바꿈 딴판 변형 전격 매듭 귀결 변환 압축 기입 서술 귀착 수정 개편 치환 탈바꿈 변경 뒤바뀌어 재 기재 다시 적혀져 써 내려가 기록 수립 도달 씌어 표기 확정 확립(can be written as)될 수도 있단 숨은 기맥힌 통찰 사실 진위 이면 팩트 가능성 쾌거 진상을 여과 숨김 거침없이 속 시원 만천하 낱낱이 파헤 수식 대수학 직접 연필 증명 보여 논파 이면 입증 제시 전파 통계 옹호 입증 전방 시사 확연 명백(Show algebraically)히 증명해내어 보십시오. 그리고 이 수리 이념 도달 증명 단행 이치 입증 완료 이후엔, 실제 그 도달 주창 논지 옹호 결부 공표 입증 증명 수리 대수학 논거 가설 진위 확정 기조 뼈대 조달 사상 사실 논법 여부 명제 전제 증명 사실 기류를 파악 공고 대조 구동 도모 단행 차원에서 다시 한 번 파이썬 컴퓨터 툴 도구(in `Python`, 교재에선 본래 실습 환경 체제로 `R`이 상정 설정 지정 기입 거론(in `R`)돼 쓰였었으나 우린 우리 코딩 분석 전산 현 파이썬 실무 문맥 환경 감안 맞춰 `Python`으로 전환 대입 통상 조율 변경 인식 이해 적용) 내부에 그들 요건 궤도 변수 실제 무작위 산출 숫치 뭉치 데이터 모형 덩이들을 여실 숫치 무더기 직업 밀어 넣 대입 우겨 수치 투입 단행 돌려 시연(numerically) 연산 도출 구동 비교 교도해 봄으로써 그 양 이면 기조 수학 연산 궤적 간 결과 덩어리가 똑 소스 일치 부합(confirm)하여 떨어지는 도출 팩트 숫자 셈법 단행 수치 증거 입증 전개 귀결 도출 증명(confirm numerically)까지 번듯 낱낱이 성사 확고히 뒷받침 마저 완료 이뤄 매듭 지어 확인 검토 종결(confirm)해 내십시오.""",

    r"**==> picture \[181 x 32\] intentionally omitted <==**":
    r"""$$ \frac{\sqrt{n-1} \sum_{i=1}^{n} x_i y_i}{\sqrt{(\sum_{i=1}^{n} x_i^2)(\sum_{i=1}^{n} y_i^2) - (\sum_{i=1}^{n} x_i y_i)^2}} $$""",

    r"   - (e) Using the results from (d), argue that the $t$-statistic for the regression of `y` onto `x` is the same as the $t$-statistic for the regression of `x` onto `y` .":
    r"""   - (e) Using the results from (d), argue that the $t$-statistic for the regression of `y` onto `x` is the same as the $t$-statistic for the regression of `x` onto `y`.
   - (e) 이 방금 바로 이 전 직전 앞 관문 코스 조항 기조 국면 단계 (d) 단락에서 귀착 발굴 증명 도출해 수집 안착 파생 산입 성과 완료해 얻어 긁어 취합 확보 구축 모아낸 제반 치환 공식 도출 수학 대수 수리 증명 진리 변형 결괏값 성과 부문 지수 무더기 산물(the results from (d))들을 일말 핵심 소중 단서 지렛대 돌파 잣대 무기 원천 활용 징검다리 병기 조달 도구 기조 투입 인자 기반으로 고스란히 끌어 안아 유효 십분 재차 유용히 발탁 차출 거듭 이용 사용 무기화 도구 차용 기용 응용(Using)함 궤도를 이끌어 필두 바탕으로, 여상 애초 목표 결괏값 타깃 변수 결과 응답 덩이 `y` 부문을 일 단면 조달 입력 근거 기준축 `x` 위로 사뿐 편입 안착 구속 얹어 종속 회귀 단행 편입(of `y` onto `x`) 연루시킨 구조 구동 전제 하 그 일련의 단순 편향 선형 회귀 모의 분석 연루 연산 단행 결과 구축 모형 체제 속 도달 위상 선상에서의 얻어진 특정 귀무 배격 판별 결판 통계 산출 점수 수위 잣대 환산 치수 고유 $t$-통계량(the t-statistic for the regression of `y` onto `x`)의 양상 덩어리 지수 점수 자체 궤적이, 외려 무자비 거꾸로 판세 기세 지수 돌려 버려 기조 역방향 스왑 역전 치환 역전 극단 뒤바꿈 거꾸로 목표 이치 기준 결과 종속 대상 응답값 척도 타깃 위상 지수 부문 대상 도달 파편 변수로 종전 잣대 도구이던 `x`를 강행 앉히고 그 이면 조달 입력 결부 의존 예측 조건 제공 유도 도구 수리 투입 바탕 원인 기구 도구 변수 자리에 버젓 외려 결괏 종속 부문이던 `y` 치수 지표를 위상 우겨 넣어 안치 얹고 결합 전도 역 도달 투입 회귀 맞부딪 역 분석 도달 기조 편입 수위 선도 강행(the regression of `x` onto `y`) 전방 연루 산입 도출 무단 수행 돌림 가동 궤도 체제에서의 파견 종착 동일 이면 해당 대응 특정 도달 연루 그 고유 발굴 성쇠 귀무 검정 결판 모종 치수 수리 지표 진위 $t$-통계량(the t-statistic for the regression of `x` onto `y`) 득세 기조 궤적 파생 도달 점수 환산 부문 덩어리 지수 수위 산입 결과 수위치와 무던 이치 놀랍토록 비교 견주나 마나 일고의 여지 하등 한 치 전혀 오차 미동 빈틈 오결 없이 양방 수치 점수 궤도 결판 환산 규모 득세 외피 결과 무더기 수준 도달 지표 지수 등락 이 진정 수학 거시 진위 기저 진상상 무관 동일 온전히 일면 완벽 어김 매한가지 똑같이 혼연일체 고스란히 이채 상응 공명 일치 거시 동일 수렴 합일(is the same as)해 떨어져 나온다는 괄목할 팩트 통찰 진실 전선 숨은 놀라운 수학 거시 명제 수위 현상 이치 진위 모종 주창 사실 사실 진전 주장 논증 사실 기조 궤도 자체를 이끌 조리 일목요연 치밀 기막 진리 논법 근거 논증 연역 확고 흔들 타당 정당화 부연 이면 설파 피력 증거 논파 타당 전선 변호 설득 주창 입증 옹호 증명 강변 논파 개진(argue)해 구축해 내 보십시오.""",

    r"   - (f) In `R` , show that when regression is performed _with_ an intercept, the $t$-statistic for $H_0$ : \beta_1 = 0 is the same for the regression of `y` onto `x` as it is for the regression of `x` onto `y` .":
    r"""   - (f) In `Python`, show that when regression is performed _with_ an intercept, the $t$-statistic for $H_0 : \beta_1 = 0$ is the same for the regression of `y` onto `x` as it is for the regression of `x` onto `y`.
   - (f) 이번엔 지례 특기 지수 제약 제한 해제 복구 정상 기조 환원 원위치 회귀 타진 상황 조치 환원상으로 거듭나서, 앞단 수위 통제 생략 도달 철회했던 그 멍에 제약 단절 고강 무리 일탈 조달 억제 탈피 절편 파트 거세 누락 강요 묵살 조항 국면 궤도를 애먼 일상 정상 상궤로 전면 되돌려 원복 갱신해 이른바 극히 보편 뭇 여느 정상 통상 평범 궤주 원칙 도리 도안 순리대로 이번 국면 시행 수심 이면에선 상수 으레 뻔한 절편(intercept) 부문 항목 점진 요소를 이변 지조 없이 결박 당당 온전 정상 수립 포함 곁들여 산입 수용 결합 동반 배정 지참 포섭 필연 개입(with an intercept) 시켜버린 확연 완전 평범 제한 무위 상태 속 온전 원형 조건 정상 궤적 온전 1차 일반 선형 회귀 구동 잣대망 일상 모의 거시 모형을 번듯 널빤 거시 산입 전력 돌려 여실 단행 수행 작동 가동(when regression is performed)시킬 발발 궤적 시퀀스 국면 궤도 때 찰나의 상황에서도, 저 앞 조위 단락 증명 산물 논파 기조 (e) 문항 이면 산출 입증 통찰 사실 현상 진위 명제 이념과 다를 바 궤주 비슷 동일 양상 진리 맥락 구도로 저 1차 선도 기울기 진전 차원 고유 계수 진입 기저 $\beta_1$ 파편 무력 소멸 헛고생 존재 의미 말소 증명 무위 가동 무용론 귀결 이탈 점화 파생 무가치 주창 허무 검정 도달 결박 이면 명제($H_0 : \beta_1 = 0$) 가설 진위 논박 기조 단안과 얽혀 종결 부합 부차 도출 환산 수립 획득 파견 결부 맞물려 지표 기조 귀환 배분되는 공용 해당 특정 고결 결판 요주의 환산 수치 산입 그 $t$-통계량(the t-statistic) 지표 환산 점수 덩어리 지수 등락 궤적 성분 자체 결론 위상만큼은, 여전히 한치 기구 예외 벗어남 없이 기응 목표 타깃 응답 반응 종속 변수 결괏 조각 결론치 축진을 `y` 로 삼고 단연 투입 인자 수치 시발 변수 예측 전건축 제공 도구 단락 위조를 `x` 로 세워 엮어 부합 편입 결합(of `y` onto `x`) 연루시켜 밀어 돌린 단안 구동 돌린 당초 궤적 단순 기본 일상 원행 선형 회귀 도달망 연산 기체 무대 기동 전선 구축 도달 거시 산출 분석 기조 도출선 위에서 획득 건져낸 점수나, 이 궤주 진위 역 뒤바꾼 치환 반전 거꾸로 결괏 종속 응답 표적 이정 타깃 위상 산입 조준 조준 치수 축 변구를 외려 `x` 로 맞대 뒤집 전도시키고 반면 진영 무리 투입 기저 파생 원인 독립 지향 측량 도구 수레 요건 조건 입력 투진 제공 지표 진입단 축을 구태 예전 종속 구경 `y` 녀석 점수판으로 삼아 부대 전용 바꿔 대입 치환 편입 전선 역전 호환 구동 결합(of `x` onto `y`) 얹어 돌림방 강행 위상 치환 역방향 연산 역순 도출 결부 가설 맞대 뒤바람 회귀 치수 궤도 결판 모형 분석망 진원 상에서 도달 포착 얻어져 뱉어 구득 차입 확보 나온 환산 모종 치수 결괏 점수나 시발 하등 한 점 모종 오동작 치차 이탈 단오 미동 헛점 편차 굴곡 흔적 일푼 소수 별반 차이 이반 간극조차 도무지 완전히 필시 털끝 틈 진작 전혀 싹 없이 거시 기조 놀랍도록 상호 동등 빈틈 일절 상명 동일 전면 매한가지 합치 이치 혼연 부합 고스란 완벽 찰떡 일치 전면 대동소이 무관 동일 치수 합일 균등 결판 이치 동률 유지 수립 발생 발현 성립 존재(is the same as)해 버린다는 그 마술 동일 사실 거시 논증 통계 미학적 이치 진리 발견 쾌거 팩트 주창 확연 현상 진위 명제 전제 도안 입증 논리선 궤적 전방 사안 결론 부문 지표 여실 가능 실증 팩트 상태 전모 정황 쾌거 사실마저도 마저 번번, 이젠 거창 입증 수학 수리 계산 종이 대수 이면 도달 공식 해체 증거 논파 공세 말구 저 당당히 이번엔 저간 컴퓨터 기저 활용 전산 연산 체계 프로그래밍 실무 코딩 언어 시뮬레이션 지표 전산 구동망 도구인 파이썬(`Python`, 물론 앞 애먼 정규 도서 지척 원문 문맥에선 `R` 기조 공용으로 여실 소개 지칭(In `R`) 되었었으나 작금 본 파이썬 전용 기반 지향 실무 번역 이면 풀이 여정 지평 맥락상 당번 기구 도구 맞춤 개조 `Python` 지수로 치환 번역 대입 호환 양해 수용 적용 관철 도입 대처 대체 투시) 코드 똬리 스크립트 작성 실험 연산 구축 난수 입력 반복 돌림 가동 구동 수리 체득 투입 실체 가설 실험 컴퓨터 실제 환산 실행 교도 과정 전선망을 고즈넉 정립 통해 숫제 대안 시연 확인 비교 단층 확립 보여(show) 실증 시현 입증 대면 과시 전파 설파 주창해 증명 시연해 보십시오.""",

    r"12. This problem involves simple linear regression without an intercept.":
    r"""12. This problem involves simple linear regression without an intercept.
12. 작금의 이번 도달 12번 문항 질의 요건(This problem) 코스 지평 역시도, 앞선 거시 궤도 부문 문항들과 지극히 유사 줄이은 기조 연장선 이면 구도 선상으로서 당장 모종 제반 거시 모델 기동축 내 무단 뻔한 절편 상수 단위 배정 파생 요건 지수 개입 자체 부문 섭리를 아예 절대 억척 일괄 절단 빼버리고 여상 지례 쏙 무단 생략 차단 철저 제거 통제 결번 절단 제외(without an intercept) 누락 배제 단행시켜 둔 특수 제약 결박 구조 일탈 국한 한정 구도 도안하의 이질 가동 특이 편차 조건 상태의, 이른바 기단 특수 제 단일 1차 단순 조달 선형 회귀 모의 방식(simple linear regression) 연산 분석 지표 모형망 궤수 구동 사안 이슈 전방 갈림길을 온통 포섭 수반 중점 심층 주안 심도 관련 연루 동반 필연 집중 다뤄(involves) 이면 파악 통찰 추적 이끌어 개진 집중 파헤칠 요량입니다.""",

    r"   - (a) Recall that the coefficient estimate \hat{\beta} for the linear regression of Y onto X without an intercept is given by (3.38). Under what circumstance is the coefficient estimate for the regression of X onto Y the same as the coefficient estimate for the regression of Y onto X ?":
    r"""   - (a) Recall that the coefficient estimate $\hat{\beta}$ for the linear regression of $Y$ onto $X$ without an intercept is given by (3.38). Under what circumstance is the coefficient estimate for the regression of $X$ onto $Y$ the same as the coefficient estimate for the regression of $Y$ onto $X$?
   - (a) 자 일단 우선, 절편 성분 따위가 무단 결손 쏙 빠져 애써 부재 제약 삭제 배제 종결(without an intercept)된 기조 투신 국면 안착 선상 구도 하에서 거시 지수 응답 응결 타깃 종속 응답 표적 $Y$ 변수 항목를 이면 입력 조준 예측 성분인 기준 잣대 도구축 $X$ 예측자 원인 지수 진영 단위 위축으로 오롯 이끌 부합 얹어 탑재 결속 단안 도달 투입 적합(of $Y$ onto $X$) 유동 연산 돌려낸 특정 단순 단편 기조 선형 회귀망 분석(for the linear regression) 궤도 모델 상의 고유 기율 핵심 기조 궤적 파생 도달 기울여 득세 요체 단관 추명 환산 예측 지표 기울기 회귀 계수 산출 추정 추이값(the coefficient estimate) 덩이 $\hat{\beta}$ 분량 성분이 어떤 모양 수리 방정식 이치 조합 공식을 띄고 애당초 귀결 산출 수립 도달 제공 단안 정의 공시 결론(is given by)지어졌었는가를, 아까 거론 짚어 살핀 앞장 본문 상 제 (3.38)번 조제 수식 등지 거시 근거 교재 문항 기록 기억들 단면 단서 등을 더듬 상기 상념 유추 회귀 상고 유념 환기 거듭 되살려 재차 번듯 기막 떠올려 상기시켜 파악 연계 회상(Recall that) 되짚어 뇌리에 기억 끄집어 환기해 보십시오. 무릇 그걸 곱씹 토대 지렛대 원흉 밑천 삼아 진단 가늠 통찰 파악 연역 도달해 보건대, 과연 도대체 어느 어떠 어떠한 모종 특수 구도 특정 특유 사안 지정 이면 연역 희소 기막 묘한 발발 기조 도달 특수 지정 으레 궤주 묘한 극단 한정 진상 구조 전개 예외 조건 극단 특별 사정 특별 조치 특별 규정 정황 한정 구도 국면 요건 주변 맥락 우연 제반 발발 극치 제척 주변 이 이질 지경 여건 지향 극단 수치 특별 상황 발현 조건 환경 우위 상태 양상 궤도하(Under what circumstance) 기경의 전면 성립 안에서 야만이 비로소, 애먼 응답 목적치 타깃 덩어리 $X$ 점수를 이면 입력 조달 근간 제공 구실 단서 부문 $Y$ 위상 위력 진영 축에 고스란 역 거꾸로 역 단안 응답 부합 역 탑재 대입 지양 도모 편입 결속 치환 적합(the regression of $X$ onto $Y$) 강제 기동 돌려 파생 얻게 발현 얻어진 저간 도달 수식 후발 이탈 역 치환 획득 수치 기울기 계수 연쇄 산입 판별 추정치(the coefficient estimate) 값 도달 분량 덩어리와, 종전 애초 정상 정방 원위 궤도대로 지상 종속 타깃 요체 응답 $Y$ 치수 녀석 자체를 오붓 제반 원인 수단 입력 지수 예측 싹수 단서 도구축 위상 $X$ 상부 기단위 진영에 정조준 원형 조달 결속 부합 탑재 포섭 귀속 온전 대입 순방 순기조 정방향 도달 안착 부응 적합(the regression of $Y$ onto $X$) 연산 구동 시연 단파 전리 도달케 해 통상 수수 거시 얻어 성취 포획 분할 도출 얻어 챙긴 애잔 정통 정식 그 원 조준 수위 발현 진상 파생 기울기 원 고유 모본 도출 회귀 계수 산출 추정 수량 분량 점수치 단위(the coefficient estimate) 덩어리 위상 크기가 영락 헛둘 하등 어김 추호 별반 편차 왜곡 일말 갈라 균열 오차 빈틈 무리 티끌 어색 별 차이 부차 단안 어금 어색 이견 분분 징후 전혀 절대 일절 일말의 엇박 다름 소폭 차 어김 치 이치 괴리 이견 전혀 부득 하나도 무 진격 없이 쌍 양 가 온전 수리 완벽 완전 공히 기이 완전 대동 동등 일치 철저 매치 등식 혼연 찰떡 거시 전면 진정 정밀 상응 기조 똑 소리 흡사 이반 일치 거시 혼연 합치 동률 상쇄 똑같이 한 몸 동일 평등 등가 수치 거시 부합 일치(is the same as) 유지 성립될 수 가능성 출현 이치 존재 여력 궤도 진전 발발 도출 쾌거 파악 형국이 극적 타결 이룩 귀결 필연 진실 마련 섭리로 발현 구성 존재 가능키나 나타나 벌어질 이치 일 수 있는 일 통달 파격 성사일지 요? 그 이유 맥 이면 조건 통찰 규명을 파헤 논술 이끌 증명 통달 답변 답파 논술해 보십시오.""",

    r"   - (b) Generate an example in `Python` with $n$ = 100 observations in which the coefficient estimate for the regression of X onto Y is _different from_ the coefficient estimate for the regression of Y onto X .":
    r"""   - (b) Generate an example in `Python` with $n = 100$ observations in which the coefficient estimate for the regression of $X$ onto $Y$ is _different from_ the coefficient estimate for the regression of $Y$ onto $X$.
   - (b) 저간 파이썬(`Python`) 전산 코딩 가상 난수 연산 시뮬레이션 지표 구동 스크립트 작성 환경 무대에 올라 전면 발발 난수 입력 투입 생성 조작 지평을 통해 인위 관측 덩이 제반 크기 표본 개수를 총 $n = 100$ 개 점 분량 위상 치수인 한 묶음 가상(observations) 무더기로 쏙 빼 도달 산입 정렬 생성 발현 창출 조달 마련(Generate an example)해 구축 보시되, 여태 기조 이번 마련 표본 추출 도출 구축 지향 데이터 지수 상에선 오붓 이른바 단안 원인 지표 목적 타깃 산입 변수 $X$ 성분값을 외려 조달 기준 잣대 축 $Y$ 예증 진상 요건 예측 기저 이면 지수 위상단 부문에 고의 뒤엎어 스왑 역전 도모 전환 편파 억지로 뒤바꾸어 대입 반대 진입 역행 편입 결속 부조 부합 적합(the regression of $X$ onto $Y$) 시 돌려 뽑혀 거시 도파 반환 귀착 기환 얻어 빼 얻어 건져 나온 도생 이면 후발 거시 치환 단안 산출 회귀 도출 파생 기울기 산입 측정 요건 계수 단안 지표 추정치 위상 덩어리(the coefficient estimate) 결괏값 규모 부문 분량이, 종전 기존 정방향 원래 원론 정석 애먼 도파 정상 줏대 종속 목푯 타깃 반응 진영 응답 $Y$ 치수 성분을 여전 흔한 오리지널 입력 연유 단서 예측자 제공 가동 기폭 기저 인자 변수 선도 도안축 $X$ 기단 위치 위로 제격 제자리 정상 원형 궤도 방식 바른 얹음 부합 이입 적합 편의 투입 산교 결합 적합(the regression of $Y$ onto $X$) 조준 순방 안착시켜 파단 기조 결합 일궈 제대로 바른 도출 도파 일구어 이면 추출 파생 산입 평면 정상 기치 거시 온전 도파 순기능 뽑아 건져 조달 낸 그 통상 오리지널 원판 정석 도출 본연 산출 무단 순수 정상 파생 예측 고유 기울기 회귀 계수 산출 추정 위상 덩이(the coefficient estimate) 크기 단위 기조 수치와 영락 얄짤 확연히 눈에 띄게 수리 이면 치수 명백 단전 다분 확연 진폭 쏠림 편차 일절 무관 현저 대다 오차 불일치 다르게(is _different from_ ) 별개 거시 극단 분분 차이 엇박 상이 위상 나뉘어 분노 구분 동떨어져 표출 양상 나타 도출 어긋 지조 나게 되는 일그러진 거시 그 한 가지 기구 특수 반례 어긋 빗나간 차이 실체 쾌거 부조 불일치 상반 이견 징후 이탈 발생 이변 모의 가상 단안 모의 샘플 시연 특이 증명 예시(example) 조각 거시 편차 판례 모의 덩이 하나를 쓱 직접 만들어 구동 입증 시현 발현 창출 도달 조립 짜내 구축 증거(Generate) 생성해 보여 증명 내십시오.""",

    r"   - (c) Generate an example in `Python` with $n$ = 100 observations in which the coefficient estimate for the regression of X onto Y is _the same as_ the coefficient estimate for the regression of Y onto X .":
    r"""   - (c) Generate an example in `Python` with $n = 100$ observations in which the coefficient estimate for the regression of $X$ onto $Y$ is _the same as_ the coefficient estimate for the regression of $Y$ onto $X$.
   - (c) 매한가지 위와 동일 연속 파이썬(`Python`) 전산 구동 막바지 지표 코딩 창출 도출 난수 생성 시나리오 가상 전선 환경 내 진입 통제 하 거두어 위상 관측 표본 거시 개수를 마저 똑같이 도두 일괄 $n = 100$ 단안 규모 개체 관측 요건 치수 집단 파편(observations) 덩어리로 통일 발굴 정렬 생성 부여 세팅 발발 생산(Generate an example)해 구축 마련해 보시되, 예의 필시 이번 갱신 요번 산입 발탁 모의 추출 발현 구성 데이터 전개 궤도 요건 속 사정에서는 마침 애석 결론 목푯 잣대 반환 응답 조달 변구 $X$ 성분 파편을 고스란 이면 예측 원인 치수 도구 단안 진입 진영 바탕 조달 위상축 $Y$ 기저단 부분 위치 위로 이면 엎어 거꾸로 스왑 반전 치환 대입 거꾸 역방 결부 부조 역 편입 종속 결합 투신 적합(the regression of $X$ onto $Y$) 강행 역풍 도파 연산 후 이면 구득 돌려 뿜어 이탈 파생 도출 산환 단안 추출 얻어져 거진 역 이파 산출 환산 도달 뽑힌 후차 치환 파생 지표 기울기 예측 억척 회귀 계수 판단 성위 지단 계수 추정치 규모(the coefficient estimate) 요건 분량이, 이전 여느 원론 보편 평범 정상 위계 원래 원형 기조 정석 궤주 종속 반응 귀결 타깃 추정 결괏 조준 덩어리 응답 $Y$ 치수 기치를 저간 순방 통상 위계 기존 일반 이치 정방 제공 입력 단초 기저 단면 부문 예측 변수 위상 발동 도달 축 $X$ 좌표 진영 부위상 위치 전면에 제격 바르게 고스란 온전 순수 정기 적소 결속 융합 안착 정순 궤주 대입 투입 결합(the regression of $Y$ onto $X$) 궤도 안치 적합 전위 기조 시켜 돌려 원래 보편 궤적 산환 도출 이변 거시 원래 구도 획득 순리 도단 기조 결속 뽑아 이득 취해 얻어 가동 구해 진 정상 오리지널 원시 도달 평범 순진 기울기 판조 통상 지표 도달 산입 위상 예측 회귀 단초 계수 덩어리 산환 추정치 규모(the coefficient estimate) 결괏 분량 점수 등단 크기와 숫제 어금 하등 이질 단차 진위 일말 편차 전혀 오차 한 점 이탈 균열 미동 미진 차이 이견 틈 엇박 간극 전혀 털끝 없이 여지 놀랍 무구 대동 전면 소이 완전 상쇄 흡사 절묘 일조 철저 부합 빈틈 판박 동률 매치 거시 동시 고스란 어김 무관 완벽 완전 똑 동등 혼연 합치 같이 매한 동일 철옹 등식 완전 이치 거시 똑같게(is _the same as_) 평치 동급 양립 동일 완전 상응 동진 일치 결착 발현 등치 부합 평형 성립되게 맞아떨어지는 바로 기이 특연 일치 부합 특수 절묘 우연 모의 희귀 합치 단안 이치 예시 전단 증명 진위 샘플 기동 덩어리 부차 이탈 발현 사례 거시 동률 실습 예제 판례 증거 조각 가상 모형(example) 한 가지 덩이를 단박 별도 스리슬쩍 또 하나 기왕 손수 만들어 꾸려 내 구축 진위 조립 시연 묘사 확립 방증 고안 제조 발현(Generate) 척척 산출 내포 시켜 입증 파단 연루 시현해 대조 제공 보여 제시 증명 내십시오.""",

    r"13. In this exercise you will create some simulated data and will fit simple linear regression models to it. Make sure to use the default random number generator with seed set to 1 prior to starting part (a) to ensure consistent results.":
    r"""13. In this exercise you will create some simulated data and will fit simple linear regression models to it. Make sure to use the default random number generator with seed set to 1 prior to starting part (a) to ensure consistent results.
13. 이제 당면한 이번 실습 예제 연습 문항 코스 도달 지평(In this exercise)에선 당신이 직접 손수 무에서 유를 빚듯 허구 관측 단편 일목 통계 인위 전위 모의 시뮬레이션 가상 궤조 가공 발생 데이터 집합군 덩어리 묶음(simulated data)들을 일렬 줄지어 낱낱이 임의 고안 창출 도달 조작 생성 구축(create)해 내 볼 참이며, 아울러 그 기단 무구 마련 조달된 내역 위상 자체를 또 도마 제물 부문 대상 기초 발판 실험 도구축으로 전폭 삼아 대입 투입해 여태 거론 단순 1차 단편 이치 단순 한 조각 일개 선형 기치 회귀 잣대 모의 단안 도출 모델군 망 수위 체제(simple linear regression models)들을 모서리 속속들이 교차 엇갈려 부합 기동 전수 적용 대입 투하 밀착 적합(fit) 연루 구동 실습도 단도 거시 강행시켜 이어가(will) 볼 것입니다. 단 도안 출발 기수 돌입 주의 명심 요건 참작 당부 기조로서, 숱한 여과 발현 산출 과정 여파 속 야기 난해 분분 난립 이탈 수위 예방 방지 차원 일환 차기 도출 산물 도파 통계 실험 재현 검토 여력 타당 거시 획득 보증 환산 담보 보존 궤적 결과 지표 성과물 파편들의 도출 진리 산입 시점마다의 흔들림 무진 일정 획일 항구 타당 거푸 고정 지조 동등 동일 유지 항경 일정 일관성 여전 부합 확보 담보 귀결 보장 지속 재현(ensure consistent results) 영구 고집 유지를 전폭 달성 일구기 위한 선행 일괄 예방 방호 확정 지렛대 단안 보조 예방 조치 탓 차편 목적 이면 까닭 이유 사방 고집 기조로서, 제일 처음 조위 최 초단 으뜸 관문 (a) 번 항구 질의 지평 시작 발단 조립 돌입 개시 전장 첫 타임 착수 시작 돌풍 착근 스타트 이점 시작 전초 점화 전야(prior to starting part (a))의 첫 삽 기치 삽질 과정 이전에, 부디 필시 어김 필연 절대 지레 단디 주의 사전 명심 다짐 각별 십분 명심 경계 거듭 유념(Make sure to)하여 당신 구동 기치 파이썬 여건 컴퓨터 프로그래밍 전산 구동 난수 함수 발생 난수 파련 난수 추출 기본 조달 배위 초기 난수 구비 팩 도출 지표 모듈 발현 기동 수치 난발 구동 원초 발생기 툴 지수 난발 형성 엔진(the default random number generator)의 태동 시드(seed) 점화 발동 기저 최초 고유 뿌리 기원 발판 지표 고정 배정 세팅 시드 점수 초기 씨앗 번호 위상 잣대값 자체를 모름지기 유념 공통 꼭 숫자 1번(`seed set to 1`)으로 동률 기조 통일 못 박 고정 족쇄 조치 할당 지정 일치 선반환 조율 부여 세팅 선행 적용 발탁 기용 부합 단속 확고 정조준 배정 설정해 조작 이용 사용 배급 기용 통일 안착(use ... set to 1)시켜 두고 일관 고정 동결 단행해야 함을 명심 지참해 통제 준수 기조 이행 진행시켜 다뤄 내십시오.""",

    r"132 3. Linear Regression \n\n": r"",

    r"- (a) Using the `normal()` method of your random number generator, create a vector, `x` , containing 100 observations drawn from a _N_ (0 _,_ 1) distribution. This represents a feature, X .":
    r"""   - (a) Using the `normal()` method of your random number generator, create a vector, `x`, containing 100 observations drawn from a $N(0, 1)$ distribution. This represents a feature, $X$.
   - (a) 방금 전 십분 공히 통제 지정 부여 세팅 안착 조율해 차출 설정해 둔 귀하 특정 시스템 상 공속 구동 전위 난수 조달 태생 점화 발생 생성기 도구 툴 모듈(your random number generator) 안에 구비 지향 탑재 얽혀 동봉된 특정 `normal()` 메서드 구동 통계 호출 명령 잣대 도구망을 십분 발췌 묶어 전격 활용 기동 투입 편입 기용(Using)함으로써, 통상 $N(0, 1)$ 정규 분포 양상 기조의 통계 수위 그물망 진영 궤적( distribution)을 모본 모체 심지 배경 삼아 안치 궤조 거기서 무구 무단 임의 무작위로 추출 지향 푹 떠서 길어 도출 차집 길어 올린(drawn from) 딱 100개 숫자 분량의 가상 개별 단단 관측 모의 덩이치 점수 개체 묶음 조각(100 observations) 파편들을 통괄 일괄 고스란 무진 한가득 모아 가득 채워 담아 포섭 품어 머금고 여태 속 지니게 통계 뭉친 채(containing) 구성 나열 편입 도출 줄 세워 조약 배열된 1차원 선형 단일 배열 성분 백터(a vector) 덩어리 지수 `x` 일개군 열 하나를 임의 쓱 전파 산입 조달 발명 고안 직조 창출 구성 연산 떡 거뜬 생성 생산 마련(create)해 돌려 보십시오. 당장 이렇게 산입 획득 뽑혀 꾸려 마련 발현 조달 집약 구축된 이 가상 모의 열 벡터 지수 덩이 무리는, 차후 전방 도달 구동될 거시 회귀 연산 모형 체제 안에서 전위 단면 예측 기준 지표 잣대 조달 통제 투입의 핵심 기저 조항 맹위 도구 지수 기준 투입 전사 파생 위력 제반 인자 요소 속성인 이른바 개입 성향 기질 성립 위상 맹위 이정 하나의 고유 단일 요건 투입 도구 잣대 원인 입력 특징 변수 세력 지표 파괴 궤적 단안 즉 수뇌 요점 $X$ 란 덩이를 거시 곧장 실체 상징 연루 모의 거론 의미 필두 대변 투사 묘사 표상 투영 상징(represents)하게 통계 기조 궤수 여건 부여 배정 자리매김 역할을 도맡아 맡아 띱니다.""",

    r"- (b) Using the `normal()` method, create a vector, `eps` , containing 100 observations drawn from a _N_ (0 _,_ 0 _._ 25) distribution—a normal distribution with mean zero and variance 0 _._ 25.":
    r"""   - (b) Using the `normal()` method, create a vector, `eps`, containing 100 observations drawn from a $N(0, 0.25)$ distribution—a normal distribution with mean zero and variance 0.25.
   - (b) 연이어 재차 동일 양상 방식 코스 부문 궤주 도파 발동 수순으로 또다시 여전 그 지겨운 똑같은 파이썬 발생기 단안 `normal()` 메서드 연산 지표 도구축을 여건 거듭 단행 기착 응용 동원 전면 차출 도달 이면 사용 재차 이용 무구 활용 투입 산입 기용(Using)하여, 다분 요번 차례엔 모단 기표 표기 국면 궤적 이탈 도안 위상 지수 통상 $N(0, 0.25)$ 로 이관 지칭 상징 거론 명기되는 또 다른 이면 지정 통계 곡선 분포 진위 기조 확률망 위상 양태 국면 선상(distribution) 내부 관할 축에서부터 이리저리 임의 난수 랜덤 우발적 떠다 발췌 도출 추출 지양 꺼내 건져 길어올려 조달 산정 산출 분배 차출 조작 유도 발췌 포획 이관 추출된(drawn from) 100개 무리 분량 묶음 개수치 분량의 관측 가상 모의 환산치 점수파 개체 개별 조각 덩이들(100 observations)을 일렬 고스란 가득 품어 한데 묶어 통괄 산입 취합 적재 통괄 품고 머금어 저장 보관 내포(containing)하여 배정 편입 얽힌 또 다른 이름표 명기 신규 별도 일차원 단면 선 일렬 열 단위 벡터 다단 성분 기조 열 `eps` 기류 조달 개체 덩어리 줄 하나를 마저 이리 한 번 두 번째로 고의 기조 변동 얽어 짜내 창출 고안 직조 단도 구축 기단 파생 산입 추가 여실 제작 빚어 도안 산출 마련 단행 조달 추가 생성(create)해 이끌어 만드십시오—이때 친절 부연 팁 기조 지양 추가 거론 첨언해 설명 참작 보충 풀이 단서 주석 부언 추가 환기 거들자면(—), 아까 위 저기 무심 언급 명기 표현 거론 열거 기술된 저 $N(0, 0.25)$ 기조 정규 분포 이관 통계 산입 모의 공식 기치 지수 잣대 수식어 문맥 꼴 양태 껍데기 위상 기호 궤적 의미가 내포 실질 시사 뜻하는 바는 기저 그 정체 본연 거위 중심 이동 구심점 축이 되는 잣대 위상 도안 수학 기조 도달 모 통계 평균(mean) 수치 결괏값 지표는 딱 고스란 한가운데 단도 오롯 완전 온전 0 즉 제로(zero) 에 영점 타겟 수렴 조밀 안착 집결 위치 포진 정착 정지해 있고, 아울러 그 주변 양옆 이반 확산 등락 넓이 폭 퍼짐 굴곡 편차 산재 조달 정도 흩어짐 도달 유동 굴절 이격 변동 조화 퍼짐 진위 척도 기조 지표인 맹위 거동 파견 위상 산입 표본 분산(variance) 지수 궤적 척도는 0.25 지표 수위 폭 넓이만큼이나 넓게 퍼져 분배 배정 기치 부과 널려 벌려 조달 세팅 투여 조치 부과 설정돼 있는, 일련 거시 무구 어떤 모종 통상 전형 보편 뻔한 이치 흔한 궤적 통상 보편 일련의 정규 분포(a normal distribution) 통계 모형 기조망 무리 양상 도안 전개 궤주 현상을 고스란 딱 정확 기치 부연 친절 상징 말해 가리켜 거들고 뜻합니다.""",

    r"- (c) Using `x` and `eps` , generate a vector `y` according to the model":
    r"""   - (c) Using `x` and `eps`, generate a vector `y` according to the model
   - (c) 그렇게 전초 기지 단계 수단 궤수 여건 방금 앞 지점에서 갓 무진 애써 무단 조도 생성 지조 발동 인위 전초 이탈 도출 확보 일궈 따끈 무척 손수 짜내 뽑아 건져 확보 구득해 세운 저 변수 조각 덩어리 열벡터 두 개 콤비 쌍, 즉 예측 단안 `x` 부문 백터 지표 열과 잔차 유동 `eps` 파생 오류 조달 덩이 벡터 나열 궤적 열 이 두 쌍둥이 기기 요소들을 이면 십분 고스란 고개 유용 복합 결탁 투입 교차 양면 배합 조합 교도 이관 매치 혼합 동원 융합 복합 양수 투입 묶어 동시 활용 기용 거시 전폭 차용 적극 엮어 동원 통합 차용 동시 거듭 묶어 공조 대입 전향 이용(Using)함으로써, 하단 이면 후위 기술 부차 덧붙 조달 나열 서술 명기 제시된 다음 저 연쇄 가설 거시 분석 도출 기반 파생 도안 수학 궤도 통계 회귀 지향 설정 단도 설계 기조 잣애 이론 통계 방정식 기저 무리 공식 도출 방정식 축 모형 모델(the model) 구조식 궤도 뼈대 기틀 이념 공식 섭리 뭇 도달 기치 요건 기준 법칙 양상 식단 선율 지표 구동 룰 규칙 조항 법도 원리 틀 설계도 전세 이치 양태 수위 잣대 꼴의 궤주 명령 체제 도리 준용 명령 단도 법칙 연쇄 의거 기저 순차 이치 요건 원안 설계 지령 가치에 전면 복종 호응 전적으로 오롯 전단 무수 절대 부합 따르고 철저 충실 의거 이안 전적 부응 준수 수긍 동의 추종 부합 결부 기조 순응 응당 입각 순응 부양 엄수 수반 기치 동조 입각 결부 적립 복종 따름 매듭 귀속 준수 수위 순순 의거(according to)하여 최후 극단 막바지 종속 반동 결괏 타깃 궤적 산출 위상 단안 맺음 귀결 반응 응답 무리 단안 종속 타깃 결전 지향 결과 벡터 요건 조준 도달 최종 추정 이치 척도 타깃 부과 산입 결과 종착 파견 덩어리 위상 열 성분 배열 지수 벡터 덩어리 단위 구슬 벡터 무리(a vector)인 `y` 실측 모의 관측 결괏 무리 나열 배열 지표 종점 타깃 성분 수위 단락 축 열을 대거 궁극 끝내 하나 거침 새로 떡 추가 창출 진위 도달 도출 전격 전개 발동 직조 기동 도파 구축 묘사 연쇄 구동 결속 계산 파생 제조 생성 산출(generate)해 마저 돌려 토해 뱉어내 일궈 파생시켜 최종 거시 성립 수립 발현 전향 구축 종결 조달해 보여내 보십시오.""",

    r"**==> picture \[182 x 11\] intentionally omitted <==**":
    r"""$$ Y = -1 + 0.5 X + \epsilon $$""",

    r"What is the length of the vector `y` ? What are the values of \beta_0 and \beta_1 in this linear model?":
    r"""What is the length of the vector `y`? What are the values of $\beta_0$ and $\beta_1$ in this linear model?
그 기조 환산 도출 지표망 결과 잣대에서 전가 끝내 토핑 종착 생산 유유 전격 발현 창출 도달 조달 조각 구동 지향 단안 산입 필지 종단 결과 구축 뱉어져 파생 얻어져 수확 튀어나온 이 최후 타깃 종속 응답 열 결괏 도달 덩이 벡터 성분 지조 궤도 나열 산물 벡터 `y` 의 궁극 내부 알맹이 꽉 찬 지표 통계 스펙 성분 갯수 점선 구성 도달 이면 함량 규모 파견 나열 개수 총체 원소 포진 전개 폭 총괄 기조 수량 나열 배열 이탈 총체 길이(the length) 사이즈 규모 개수는 단연 도대체 최종 통계 도합 딱 몇 개 숫자 덩이 조각 길이라 단언 환산 규정 필연 집계 규명 귀결 귀착 총계 파악 결정 계산 세팅 집계 맺어지게 환선 단정 세어 셀 지정 산출 귀속 결론 나옵디까(What is)? 아울러 당장 위 산입 적시 투입 전개 기술 묘사된 저 임의 시각 가상 인위 교본 궤주 통상 조작 지정 도안 시사 거시 배정 가상 허상 구조 도안 이면 도출 무구 단순 기반 기전 단도 단편 1차 일방 회귀 선형 무단 투입 설정 지정 산술 인조 궤도 기조 분석 거시 가동 모형(this linear model) 기단 식 껍데기 틀 잣대 이중 척도 구동 방정식 내부 골자 진영 이면 궤도 속에서, 일일 당초 이탈 묵과 요체 거시 회귀 억제 기본 잣대 도출 단면 계수 척도 단초 고유 참값 위치 위상 변위 지위 요소 핵심 기둥 성분 위치 거위 조달 기치 덩이들을 대변 투사 포진 차지 점령 점유 수행 포괄 지표 선도 이관 기명 위임 지령 으레 암시 지지 발현 속성 의미 부위 발동 부여 수위 점유 대행 담보 맹위 이관 표방 점 지칭 표기 지표 차출 표상 상징 떠맡고 배정 차리 속해 도맡아 배 속 대리 띠고 차지 조달 위치 있는 그 뭇 도달 해당 두 중요 파생 기치 매개 산입 요인 속성 인자 특정 상수 결부 핵심 이치 지수 본 뼈대 상수 성분 매개체 기단 매개 변수들 제반 파편 요건 기조 단초 지표인 즉 저 이른바 모 가설 $\beta_0$(기저 진 실체 모집단 오리지널 회귀 모델 제로 지수 참 절편 결곳 뼈 기조 고유 진짜 태생 오리지널 상수 참치 본 연산 상수 본판 원래 참 모집단 실제 실 진리 상수 태고 정답 궤도 절편치수) 성분 기조 통상 이치 요체 지표 계수 성분과 또 연이어 이면 바로 덧붙 옆자리 진격 도출 이어진 파단 동반 한 몸 저 부차 기울기 궤조 동행 지향 이면 동격 이관 진 파견 $\beta_1$(실 기단 이면 오매불망 태생 오리지널 원 모집단 실 기조 참 진짜 정답 기울기 태고 단안 유별 원래 기단 잣대 조도 고유 회귀 참 뼈 본판 모집 변위 편차 기치 속성 덩이 파단 기울기 원래 참치수 도출 환산 본 계수치) 조준 항목 진단 요체 이 수위 특정 도도 기치 부문 상수 변도 지표 분량 점수 두 파생 고유 모 기저 변조 계수 항목 편차 부문 상수 덩이 이들 기체 파견 본 수위 단위 잣대 위상 분량 고유치 항목 지표 치수 값성분(the values) 조각 제반 덩어리 전위 점수 위력 성분 부문 기득 위상 크기 본 치수 지표 점수들은 각각 도통 결부 정체 궤적 결단 단도 실체 도합 정작 대체 무척 정확 속시 얼마라는 수치 숫자 분량 척도 점수로 애먼 각자 정작 얼마얼마 단언 필연 수리 규정 도출 배속 필시 부여 표기 지정 결박 단언 기입 적체 환산 진단 파악 얼마로 단연 기입 규명 속 시 명백 정립 얼마라 지목 판가름 확립 얼마 얼마라 할 속 속히 이치 특정 섭리 명쾌 기치 얼마라 세팅 발현 딱 떨어지기 귀착 굳어 결정 세팅 귀속 포섭 단언 세팅 설정 할 수 도출 결정 단박 귀결 될 얼마 수위 숫자 점수 분과 분량 수리 통계 점수 치수들 결론 지정 요건 지수이라 할 기입 명시 지정 파악 필지 얼마요 얼마라 진단 표본 수 조달 단안 할 수 점철 속 발굴 배정 파 단연 속 환결 결결 정립 진척 규명 수립 결속 얼마라 명명 이관 할 지치 궤 가결 입 입 수 결결 기기 파 얼마 파 기결 도 결 기 파얼마 수 결 단 결조 발발 도출 도달 기기 기 파 결 파 조 파 기 결 조기조 발 단지 되 성기 결결 판 가 단 부 부 부기 정기 다 조결 무 단기결 모 얼마 입 조 가 지 기무조 기 기 얼(What are) 파 얼 진 얼 조 구 조 다 진 조 조 파 기 도 결 진 조 판 결 무 부 진 기 결 기조 기 지 무 도 조 조 결 구 도 조조얼마 구 기 파조 니까?
