import codecs

content = """
![Figure 6.24](./img/6_24.png)

**FIGURE 6.24.** _The lasso was performed with $n = 100$ observations and three values of $p$, the number of features. Of the $p$ features, 20 were associated with the response. The boxplots show the test MSEs that result using three different values of the tuning parameter $\lambda$ in (6.7). For ease of interpretation, rather than reporting $\lambda$, the_ degrees of freedom _are reported; for the lasso this turns out to be simply the number of estimated non-zero coefficients. When $p=20$, the lowest test $\text{MSE}$ was obtained with the smallest amount of regularization. When $p=50$, the lowest test $\text{MSE}$ was achieved when there is a substantial amount of regularization. When $p=2,000$ the lasso performed poorly regardless of the amount of regularization, due to the fact that only 20 of the 2,000 features truly are associated with the outcome._
**그림 6.24.** _고차원 세팅 환경에서 측정 관측치 개수를 고정 상수 $n = 100$으로 세팅하고 모형 투입 피처 특성 수치 할당 차원 지수 $p$의 크기를 세 가지 각각 다른 척도로 통제 교차 배정 적용하여 라쏘(lasso) 추론 평가를 수행 관측해 본 테스트 성과 추이 곡선 궤도 도식 모음입니다. 이 총 각 지정 할당된 여러 $p$개의 특성 중 오직 오리지널 20개의 특성 단위만이 진정으로 결과 반응 변수 타겟과 유의하게 엮인 연관성 연동 지표 진단을 받아 단절 없이 끈끈하게 세팅되어 있습니다. 전시 배열된 상자 그래프 표기(boxplots) 도면 뷰는 정규 평 준 조절 (6.7) 공식에서 파생되는 튜닝 제어 조절 매개 파라미터 $\lambda$ 수치율을 각각 다른 세 가지 규격 세팅 변경 단계로 조여 두고 무대 테스트 평가를 돌려 측정 산출 평가해 낸 종단 테스트 $\text{MSE}$ 오답 성적을 보여 줍니다. 이해 해석과 표기 시각 편의 도모 측면의 용이함을 달성 위해, 번거롭게 $\lambda$ 배수 지수를 일일이 직접 수리 표기 언급하는 대신, 이 도식상 결과 축에는 대체 측정으로 이른바 자유도 조절(degrees of freedom) 척도가 환산 보고 반영되었으며; 이 실험 대상 기준 모델이 라쏘(lasso) 구조 시스템인 점을 감안할 때 그 규격 산출 자유도 통제 측정 개수 환산 치는 단순히 모델 예측 도달 판별상 0이 아닌 수치 값으로 유효하게 살아남아 추정된 산출 비제로 계수 개수 지표 만을 단순 일괄 투영 일치시켰음을 뜻합니다. 평가 환경 세팅이 $p=20$인 기초 구간일 때, 그 모델 통계 평가상 단면의 최저 최하점 최소 오차율 우수 성적을 뜻하는 최저 테스트 측정 $\text{MSE}$가 가장 모델에 헐렁하게 적은 최소량의 여유 규제를 가했을 때 성공적으로 도출 획득됨을 살필 수 있습니다. $p=50$ 단락 모델 세팅일 때는, 다소 상당량의 거센 강한 모델 페널티 단면 규제가 모형 진영에 강하게 가해졌을 때 비로소 최저 최하점 우수 최저 테스트 수차 $\text{MSE}$가 모델 방어 산출 한계망에서 아슬 달성 성공됨을 목측합니다. 파멸의 $p=2,000$ 극한 고차원 수 통 관 세팅 진영에서는 얼마나 지독하게 양방향 규제 패널티 양을 가하든 상관없이 시스템 산출 모델의 라쏘 성과는 속절없이 무참하게 모델 편차 밖으로 벗어나 형편없이 무너지며 도출 측정되었는데, 이는 전체 우주 2,000개의 방방곡곡 개수 특성 파라미터 변수들 중 기껏 고작 20개 소수 변수만이 실제 오리지널 참된 진짜 결과 종점 관련 반응과 끈이 연결되어 유의 연계되어 있다는 그 허망한 태생 실측 사실 구조적 원리 여건상 기인 때문입니다._

In Section 6.1.3, we saw a number of approaches for adjusting the training set RSS or $R^2$ in order to account for the number of variables used to fit a least squares model. Unfortunately, the $C_p$, AIC, and BIC approaches are not appropriate in the high-dimensional setting, because estimating $\hat{\sigma}^2$ is problematic. (For instance, the formula for $\hat{\sigma}^2$ from Chapter 3 yields an estimate $\hat{\sigma}^2 = 0$ in this setting.) Similarly, problems arise in the application of adjusted $R^2$ in the high-dimensional setting, since one can easily obtain a model with an adjusted $R^2$ value of 1. Clearly, alternative approaches that are better-suited to the high-dimensional setting are required.
앞선 구조인 6.1.3절 단면 파트에서, 우리는 최소 제곱 추정 모델 시스템을 적합하기 이전에 이 무대 진영 동원에 이용된 가변성 측정 지표 변수 총 개수 통제 치수를 반영 조치하기 위해 훈련 모의 파트 세트상 측정 오차 단위인 수치 $\text{RSS}$ 통계나 혹은 모형 척도 조율 $R^2$ 지표율 단위 등을 일부 조작 통제 보정해 편제 제어하는 무수한 수단 접근 방식 대안들을 여럿 파헤쳐 살폈습니다. 너무나도 애석하게도 이런 눈속임 대안들로 꼽혔던 그 유명한 $C_p$, $\text{AIC}$, 그리고 $\text{BIC}$ 기법 추론 접근 통계 수리법 구상들은 지금 이런 과도한 고차원 예측 모델 세팅 환경 진영에서는 절대 맞들어 부합되지 못하며 모델 구축 적합 단면에 전혀 쓸모없어 부적합합니다. 왜냐하면 고차원에선 분산 추정치 지수 $\hat{\sigma}^2$를 도출 단면 연산 계산 측량해 내는 행위 그 시도 여부 자체가 구조 단면 성질적으로 이미 너무 무지막지하게 비논리적이라 치명적인 심각한 부수 모순 문제가 파생 발발하기 때문입니다. (가령, 3장 모의 과정에서 다룬 $\hat{\sigma}^2$ 기본 연산 추론 공식을, 꽉 막힌 이런 고차원 시스템 세팅 환경 궤도에 융통성 없이 무지하게 투입 대입해 돌려버리면 고차원 태생상 그 추정 측정 결괏값이 무조건 모조리 계산 공식 $\hat{\sigma}^2 = 0$ 이 기형적 모순 도출 산출 전복되어 텅 빈 영 무 영 값이 붕괴 귀결되어 전도 파탄 나 버립니다.) 이와 동일한 궤도의 모순 문제로, 편법 계산 적용의 조정된 모의 $R^2$ 구조를 이런 고차원 세팅 환경에 끌어들여 오답 무결 적용할 때도 똑같은 부수 문제점들이 파생 발발 수리 유입됩니다. 왜냐하면 이렇게 측정 모델의 한계를 압도하는 무수한 투과 모델 데이터 차원 틈에선, 마음만 먹으면 피처 개수 변수를 억지로 쥐어짜 집어넣어 구색 지표로 누구든 너무 쉽고도 쉽게 조정된 판별 모델 $R^2$ 평가 무결 최종값이 무려 최고점 1로 달성 기록 측정되는 기형 도출 기적의 눈가림 기형 완벽 사기 모의 모델 수리를 어렵지 않게 가뿐히 얻어낼 모방 산출을 이룩할 수 있기 때문입니다. 결론적으로 자명히 명백하게 단절되다시피, 이렇게 특수하게 한 편의 차원에만 치우쳐 기우는 비대한 고차원 세팅 환경 단면 분석 무대에 걸맞게 훨씬 더 유동적이고 잘 튼튼히 조율 부합되는 완전히 새로운 신식 대안적 모델 파생 구조 접근 패러다임 방식 해결책 기조들이 앞으로의 통계 진영 모델 수리 예측 미래엔 반드시 모색 강구 강력히 모 조 요구 갈망되고 분명 필 요 부 단 절 구 축 수 위 요 망 합 니 다.
"""

try:
    with open(r'd:\site\jinydev\Statistical\src\book\c06\6_4_considerations_in_high_dimensions\6_4_2_what_goes_wrong_in_high_dimensions\trans2.md', 'a', encoding='utf-8') as f:
        f.write(content)
except Exception as e:
    print(e)
