import codecs

content = """
Figure 6.23 further illustrates the risk of carelessly applying least squares when the number of features $p$ is large. Data were simulated with $n = 20$ observations, and regression was performed with between 1 and 20 features, each of which was completely unrelated to the response. As shown in the figure, the model $R^2$ increases to 1 as the number of features included in the model increases, and correspondingly the training set $\text{MSE}$ decreases to 0 as the number of features increases, _even though the features are completely unrelated to the response_. On the other hand, the $\text{MSE}$ on an _independent test set_ becomes extremely large as the number of features included in the model increases, because including the additional predictors leads to a vast increase in the variance of the coefficient estimates. Looking at the test set MSE, it is clear that the best model contains at most a few variables. However, someone who carelessly examines only the $R^2$ or the training set $\text{MSE}$ might erroneously conclude that the model with the greatest number of variables is best. This indicates the importance of applying extra care when analyzing data sets with a large number of variables, and of always evaluating model performance on an independent test set.
그림 6.23 도면은 통계 투입 특성의 개수인 $p$가 클 때 이렇게 부주의하게 막무가내로 최소 제곱 기법을 함부로 적용하는 행위의 치명적 위험성을 훨씬 더 적나라하게 경고해 묘사합니다. 총 $n = 20$개의 단단한 관측치 객체로 가상 시뮬레이션 합성된 데이터상에, 1개부터 최대 20개 사이의 다중 피처 특성을 집어넣어 회귀 추론을 수행해 봅니다. 이때 투입시킨 모든 예측 특성 변수들은 애당초 목표 반응 타겟 변수 방향과는 정말 눈곱만큼도 관계없이 제멋대로 노는 완전히 독립적 무작위 가짜 값들이었습니다. 그런데 그림 산출 뷰에서 알 수 있듯, 모델 훈련망에 투입 포함시키는 가짜 특성 개수가 점진적으로 하나둘 늘어날수록 마법처럼 훈련 세트 $R^2$ 점수는 비상식적으로 거짓말처럼 1을 향해 뚫고 치솟으며, 동시에 훈련 모델 세트 측 평가 $\text{MSE}$ 지수는 꿈속의 오차율 제로인 0을 향해 점진 감소해 수렴합니다. _심지어 모델에 밀어 넣은 예측 특성 피처들이 실제 판별 종점 반응 점수엔 완전히 일말의 상관도 없고 일치 안 하는 무의미한 독립 요소임에도 불구하고 일어나는(even though the features are completely unrelated to the response)_ 파멸적 수리적 통계 마술 착시 눈속임 현상입니다. 하지만 이 동전 뒷면으로 역전해 단면 독립적인 공간으로 격리된 새로운 별개 자원 무대인 _독립 분할 테스트 검증 세트(independent test set)_ 진영 내의 검증 $\text{MSE}$ 수치는 훈련 통계와는 다르게 모형 변수의 수가 추가될수록 우주 폭발하듯 극렬 거대하게 터져 치솟게 됩니다. 쓸모없는 가변성 단면 부가 예측 변수를 닥치는 대로 닥닥 긁어 모형에 꾸역 끼워 넣고 투입을 남발하는 행위는 결국 측정 추정 계수 변동 폭, 즉 어마무시한 통제 불능 분산(variance)의 극한 변동 증폭 확산을 막대하게 자극해버리기 때문입니다. 평가 잔차 테스트 측 오차 계산 통계 MSE를 냉정하게 객관적으로만 살피면, 기껏해야 아주 극소수 소수의 통제 변수만을 남겨 차용한 한정 모델 구조가 명백하게 가장 빛나는 최고의 최적 성능을 찍는 베스트 모델임이 자명해집니다. 하지만 이러한 고차원 데이터의 무서운 속내 모순을 간과한 채, 섣불리 단순하게 눈가림 척도인 모의 $R^2$ 지표나 당장 눈앞 모델 측정 진영의 편향적 훈련 오류 모의 $\text{MSE}$ 평가 수치만 얕게 치중해 살피는 사람은 변수를 최대한 많이 무식하게 끌어모은 과적합 돼지 피처 모델이 가당찮게 가장 최고라는 최악의 잘못된 헛발질 착각 결론에 빠지고 말 것입니다. 이 사태는 막대한 수치 단위 예측 배열 변수들을 보유한 거대 관측 고차원 데이터 진영 분석 무대에서 절대적 경각심 주의 통제 방식 잣대를 강제 적용해야 함과 동시에, 항상 무조건 최종 판단 모델 도출 성능 평가는 철저 완벽하게 격리 확보 통제된 분리 궤도 상 외부 척도의 독립 단면 테스트 세트 무대 상에서 엄격히 치러 단행 판별하는 습관이 목숨만큼 중요하다는 것을 적나라하게 가르쳐 줍니다.
"""

try:
    with open(r'd:\site\jinydev\Statistical\src\book\c06\6_4_considerations_in_high_dimensions\6_4_2_what_goes_wrong_in_high_dimensions\trans2.md', 'a', encoding='utf-8') as f:
        f.write(content)
except Exception as e:
    print(e)
