import sys

file_path = r"d:\site\jinydev\Statistical\src\book\c03\3_2_multiple_linear_regression\3_2_2_some_important_questions\3_2_2_2_three_model_fit\index.md"
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "# Three: Model Fit": "# Three: Model Fit \n# 세 번째 단계: 모델 적합",
    
    "Two of the most common numerical measures of model fit are the RSE and $R^2$ , the fraction of variance explained. These quantities are computed and interpreted in the same fashion as for simple linear regression.":
    "Two of the most common numerical measures of model fit are the RSE and $R^2$, the fraction of variance explained.\n모델 적합도를 수치적으로 측정하는 가장 일반적인 척도 두 가지는 RSE 와 분산의 설명 비율인 $R^2$ 입니다.\n\nThese quantities are computed and interpreted in the same fashion as for simple linear regression.\n이 척도들은 단순 선형 회귀에서와 동일한 방식으로 계산되고 해석됩니다.",
    
    "Recall that in simple regression, $R^2$ is the square of the correlation of the response and the variable. In multiple linear regression, it turns out that it equals ${	ext{Cor}(Y, \\hat{Y})}^2$ , the square of the correlation between the response and the fitted linear model; in fact one property of the fitted linear model is that it maximizes this correlation among all possible linear models.":
    "Recall that in simple regression, $R^2$ is the square of the correlation of the response and the variable.\n단순 회귀 분석에서 $R^2$ 가 응답 변수와 예측 변수 간 상관계수의 제곱이었음을 상기해 보십시오.\n\nIn multiple linear regression, it turns out that it equals $\\text{Cor}(Y, \\hat{Y})^2$, the square of the correlation between the response and the fitted linear model; in fact one property of the fitted linear model is that it maximizes this correlation among all possible linear models.\n다중 선형 회귀에서, 이 값은 응답 변수와 적합된 선형 모델 간 상관계수의 제곱인 $\\text{Cor}(Y, \\hat{Y})^2$ 와 같다고 판명납니다; 사실 적합된 선형 모델의 한 가지 속성은 이 수식이 가능한 모든 선형 모델들 중에서 상관계수를 최대로 만든다는 것입니다.",
    
    "An $R^2$ value close to 1 indicates that the model explains a large portion of the variance in the response variable. As an example, we saw in Table 3.6 that for the `Advertising` data, the model that uses all three advertising media to predict `sales` has an $R^2$ of 0 _._ 8972. On the other hand, the model that uses only `TV` and `radio` to predict `sales` has an $R^2$ value of 0 _._ 89719. In other words, there is a _small_ increase in $R^2$ if we include newspaper advertising in the model that already contains TV and radio advertising, even though we saw earlier that the $p$-value for newspaper advertising in Table 3.4 is not significant. It turns out that $R^2$ will always increase when more variables are added to the model, even if those variables are only weakly associated with the response. This is due to the fact that adding another variable always results in a decrease in the residual sum of squares on the training data (though not necessarily the testing data). Thus, the $R^2$ statistic, which is also computed on the training data, must increase. The fact that adding newspaper advertising to the model containing only TV and radio advertising leads to just a tiny increase in $R^2$ provides additional evidence that `newspaper` can be dropped from the model. Essentially, `newspaper` provides no real improvement in the model fit to the training samples, and its inclusion will likely lead to poor results on independent test samples due to overfitting.":
    "An $R^2$ value close to 1 indicates that the model explains a large portion of the variance in the response variable.\n1에 가까운 $R^2$ 값은 모델이 응답 변수 내에 분산된 형태의 많은 부분을 설명하고 있음을 나타냅니다.\n\nAs an example, we saw in Table 3.6 that for the `Advertising` data, the model that uses all three advertising media to predict `sales` has an $R^2$ of $0.8972$.\n예를 들어, 표 3.6 에서 보았듯이 `Advertising` 데이터의 경우, `sales` 예측을 위해 세 가지 광고 매체를 모두 사용하는 모델은 $0.8972$ 의 $R^2$ 를 가집니다.\n\nOn the other hand, the model that uses only `TV` and `radio` to predict `sales` has an $R^2$ value of $0.89719$.\n반면에, `sales` 예측을 위해 `TV` 와 `radio` 두 매체만 사용하는 모델은 $0.89719$ 의 $R^2$ 값을 가집니다.\n\nIn other words, there is a _small_ increase in $R^2$ if we include newspaper advertising in the model that already contains TV and radio advertising, even though we saw earlier that the $p$-value for newspaper advertising in Table 3.4 is not significant.\n다시 말해서, 비록 우리가 앞서 표 3.4 에서 신문 광고의 $p$-값이 유의하지 않음을 보았음에도 불구하고, 이미 TV 와 라디오 광고를 포함하고 있는 모델에 신문 광고 매체 항목을 추가하면 $R^2$ 에서 _근소한(small)_ 증가가 발생합니다.\n\nIt turns out that $R^2$ will always increase when more variables are added to the model, even if those variables are only weakly associated with the response.\n이렇듯 변수들이 응답 변수와 단지 아주 미약하게 연관되어 있다 할지라도, 모델에 더 많은 변수 항목들이 추가될 때마다 $R^2$ 는 항상 증가하게 되는 것으로 밝혀집니다.\n\nThis is due to the fact that adding another variable always results in a decrease in the residual sum of squares on the training data (though not necessarily the testing data).\n이것은 또 다른 변수를 추가하는 행위가 (테스트 데이터에서는 반드시 그렇지는 않을지언정) 훈련 데이터 상의 잔차 제곱합에서 항상 자연스러운 감소를 초래한다는 사실 때문입니다.\n\nThus, the $R^2$ statistic, which is also computed on the training data, must increase.\n따라서, 마찬가지로 훈련 데이터를 기반으로 계산되는 $R^2$ 통계량은 반드시 증가해야만 합니다.\n\nThe fact that adding newspaper advertising to the model containing only TV and radio advertising leads to just a tiny increase in $R^2$ provides additional evidence that `newspaper` can be dropped from the model.\n오직 TV 및 라디오 광고만을 포함하는 모델에 신문 광고를 추가하는 것이 단지 아주 적은 양의 $R^2$ 증가 수치만을 이끌어 낸다는 사실은 결과적으로 해당 모델에서 `newspaper` 항목을 과감히 제외시켜도 된다는 추가적인 증거를 제공합니다.\n\nEssentially, `newspaper` provides no real improvement in the model fit to the training samples, and its inclusion will likely lead to poor results on independent test samples due to overfitting.\n본질적으로, `newspaper` 항목은 훈련 표본에 적합화된 모델 내에서 어떠한 실질적인 개선도 제공하지 못하며, 이것의 무리한 포함 시도는 오히려 일종의 과적합(overfitting)으로 인해 독립적인 테스트 표본에서 더 좋지 못한 결괏값을 야기할 가능성이 높습니다.",
    
    "By contrast, the model containing only `TV` as a predictor had an $R^2$ of 0 _._ 61 (Table 3.2). Adding `radio` to the model leads to a substantial improvement in $R^2$ . This implies that a model that uses TV and radio expenditures to predict sales is substantially better than one that uses only TV advertising. We could further quantify this improvement by looking at the $p$-value for the `radio` coefficient in a model that contains only `TV` and `radio` as predictors.":
    "By contrast, the model containing only `TV` as a predictor had an $R^2$ of $0.61$ (Table 3.2).\n그와는 대조적으로, 예측 변수로 오직 `TV` 하나만 담고 있던 모델은 $0.61$ 의 결정 계수인 $R^2$ 값(표 3.2)을 기록했습니다.\n\nAdding `radio` to the model leads to a substantial improvement in $R^2$.\n해당 모델에 `radio` 항목을 덧붙이는 것은 $R^2$ 수치에 아주 상당한 수준의 개선을 초래합니다.\n\nThis implies that a model that uses TV and radio expenditures to predict sales is substantially better than one that uses only TV advertising.\n이것은 다시 말해 매출을 예측할 때 TV 그리고 라디오 지출분 모두를 투입하는 모델이, 오로지 TV 단일 광고 매체 수단만 단독으로 사용하는 시스템 모델보다 전반적으로 월등히 더 낫다는 점을 시사합니다.\n\nWe could further quantify this improvement by looking at the $p$-value for the `radio` coefficient in a model that contains only `TV` and `radio` as predictors.\n오로지 `TV` 와 `radio` 두 요소만을 단독 예측 변수로 차용하는 모델 내에서 `radio` 계수에 해당하는 $p$-값을 면밀히 살펴봄으로써, 우리는 이 개선도를 한층 더 수량화해 낼 수 있습니다.",
    
    "The model that contains only `TV` and `radio` as predictors has an RSE of 1.681, and the model that also contains `newspaper` as a predictor has an RSE of 1.686 (Table 3.6). In contrast, the model that contains only `TV` has an RSE of 3 _._ 26 (Table 3.2). This corroborates our previous conclusion that a model that uses TV and radio expenditures to predict sales is much more accurate (on the training data) than one that only uses TV spending. Furthermore, given that TV and radio expenditures are used as predictors, there is no point in also using newspaper spending as a predictor in the model. The observant reader may wonder how RSE can increase when `newspaper` is added to the model given that RSS must decrease. In general RSE is defined as":
    "The model that contains only `TV` and `radio` as predictors has an RSE of 1.681, and the model that also contains `newspaper` as a predictor has an RSE of 1.686 (Table 3.6).\n대개 `TV` 와 `radio` 둘만을 변수 항목으로 취급하는 모델의 경우 1.681 이라는 일관된 RSE 체제를 점유하고 있으며, 이에 덧붙여 부가 예측 인자로 `newspaper` 요소까지 동원하는 해당 모델은 1.686 등급의 RSE 치를 보여줍니다(표 3.6).\n\nIn contrast, the model that contains only `TV` has an RSE of $3.26$ (Table 3.2).\n이와 대조적으로 오직 단일로 `TV` 만 취하는 이 모델 형식의 RSE 단위 수치는 $3.26$ (표 3.2) 에 다다릅니다.\n\nThis corroborates our previous conclusion that a model that uses TV and radio expenditures to predict sales is much more accurate (on the training data) than one that only uses TV spending.\n이 점은 이전부터 쭉 지켜 봐왔듯 TV 지표와 더불어 다방면의 매스미디어에 속출하는 라디오 방송 송출 지출 비용 구조를 복합 활용하여 매출 실적을 유추해 나가는 모델 그 자체의 분석 모형이 오직 독자적인 구조의 TV 투자 지출에 의지하는 방식보다 훨씬 더 오차 측면에서 통계적으로 정확하다(훈련 데이터 상에서)는 우리의 이전 단정적 결론을 강하게 뒷받침해 주는 모양새와 같습니다.\n\nFurthermore, given that TV and radio expenditures are used as predictors, there is no point in also using newspaper spending as a predictor in the model.\n더 나아가서 위와 비슷한 견지에서 TV 지출 항목과 라디오 비용 내역 두 구조물이 주된 예측 변수로 동시 쓰인다는 사실 그 자체에 근거해 보았을 때, 모델 체제 속에서 굳이 신문 배포 비용 내역을 여타의 또 다른 부수 예측 변수 자격으로 취해 봐야 득이 될 어떠한 특별한 이점조차 존재하지 않는다는 사실 역시 명명백백합니다.\n\nThe observant reader may wonder how RSE can increase when `newspaper` is added to the model given that RSS must decrease. In general RSE is defined as\n관찰력이 뛰어난 독자라면 마땅히 RSS 수치는 감소해야 함에도 불구하고 막상 `newspaper` 항목을 새롭게 추가했을 때 어째서 도리어 이 잔차 표준 오차(RSE) 가 외려 이리 상승 곡선을 그리는지 내내 의아해할지도 모릅니다. 일반적으로 RSE 는 통상 다음과 같이 명확히 정의됩니다.",
    
    "**FIGURE 3.5.** _For the_ `Advertising` _data, a linear regression fit to_ `sales` _using_ `TV` _and_ `radio` _as predictors. From the pattern of the residuals, we can see that there is a pronounced non-linear relationship in the data. The positive residuals (those visible above the surface), tend to lie along the 45-degree line, where TV and Radio budgets are split evenly. The negative residuals (most not visible), tend to lie away from this line, where budgets are more lopsided._":
    "**FIGURE 3.5.** _For the_ `Advertising` _data, a linear regression fit to_ `sales` _using_ `TV` _and_ `radio` _as predictors. From the pattern of the residuals, we can see that there is a pronounced non-linear relationship in the data. The positive residuals (those visible above the surface), tend to lie along the 45-degree line, where TV and Radio budgets are split evenly. The negative residuals (most not visible), tend to lie away from this line, where budgets are more lopsided._ \n**FIGURE 3.5.** `Advertising` _데이터에 대해, 예측 인자로써 각각_ `TV` _와_ `radio` _매체를 기용한 다음 이를_ `sales` _항목상에 선형 회귀로 적합화한 모습._ _표시된 잔차 분포 모형의 단면 패턴을 통해 우리는 이 데이터 항목 군들 사이에 극히 두드러지는 특유의 비선형적 관계성이 분명히 다소 뚜렷하게 짙게 내포되어 있음을 한눈에 쉽사리 도출해 볼 수 있습니다._ _잔류 값이 전부 양수인 양의 잔차(surface 평면 위로 보일 듯 고개를 살며시 내민 쪽)들만 놓고 보면, 대개 이들은 주로 TV 지표와 라디오 비용 예산안 수준이 절반 기준치로 어느 정도 고르게 양분된, 도표 한가운데 놓인 대략 45도 기울기의 중심 등분선을 주축 삼아 나란히 나열되려고 하는 일정한 일직선상의 형태적 경향성을 지닙니다._ _이와 맞물려 반대로 위치한 음의 잔차(절대다수가 평면 덮개 아래 위치해 대부분 시야각에서 가려진 무리)들의 경우에는 대체로 두 영역의 예산 편성률이 대단히 어느 한쪽으로 다소 지나칠 만치 크게 편중된 특정 구역인, 위에서 언급한 해당 기준 격 등분 분단선 밖을 벗어나 어딘가 뚝 떨어진 별방 부근에 머물고자 하는 듯한 배치 경향을 한결같이 강하게 보입니다._",
    
    "which simplifies to (3.15) for a simple linear regression. Thus, models with more variables can have higher RSE if the decrease in RSS is small relative to the increase in $p$ .":
    "which simplifies to (3.15) for a simple linear regression.\n이 셈법 식은 그저 단순한 형태의 선형 회귀 방식의 경우 곧바로 (3.15) 수식 구조 하나로 단순하게 간소화됩니다.\n\nThus, models with more variables can have higher RSE if the decrease in RSS is small relative to the increase in $p$.\n따라서 조금 더 폭넓은 숫자의 독립 변수를 두루 거느린 모델들은 기껏 도출된 RSS 감소 성분치가 $p$ 지표 단위 숫자의 오름폭과 견주어 상대적으로 아주 소박할 판국이라면 이로 인해 기존 대비 제법 한층 더 상향된 RSE 기록을 여과 없이 거머쥘 수도 있습니다.",
    
    "In addition to looking at the RSE and $R^2$ statistics just discussed, it can be useful to plot the data. Graphical summaries can reveal problems with a model that are not visible from numerical statistics. For example, Figure 3.5 displays a three-dimensional plot of `TV` and `radio` versus `sales` . We see that some observations lie above and some observations lie below the least squares regression plane. In particular, the linear model seems to overestimate `sales` for instances in which most of the advertising money was spent exclusively on either `TV` or `radio` . It underestimates `sales` for instances where the budget was split between the two media. This pronounced non-linear pattern suggests a _synergy_ or _interaction_ effect between interaction the advertising media, whereby combining the media together results in a bigger boost to sales than using any single medium. In Section 3.3.2, we will discuss extending the linear model to accommodate such synergistic effects through the use of interaction terms.":
    "In addition to looking at the RSE and $R^2$ statistics just discussed, it can be useful to plot the data.\n방금 조목조목 논의한 RSE 및 $R^2$ 부문 통계량을 면밀히 관찰하는 것 이외에도, 데이터를 그래픽 플롯(plot) 구도로 나란히 직접 그려 내는 투사 작업 행위 역시 분명히 은근히 쏠쏠한 유용성을 제공할 수 있습니다.\n\nGraphical summaries can reveal problems with a model that are not visible from numerical statistics.\n수치적 통계량 자체만으로는 가시적으로 잘 포착되지 않는 모델 속 내부 고유의 잠재적 숨은 문제점들을 이러한 시각적 측면의 다양한 그래픽 요약 도구들이 종종 투명하게 드러내 줄 수도 있기 마련입니다.\n\nFor example, Figure 3.5 displays a three-dimensional plot of `TV` and `radio` versus `sales`.\n일례로 그림 3.5 가 투사해 내는 형태인 `sales` 측 대비 `TV` 표기선과 `radio` 투시각 입체 형상의 3차원 단면 플롯 결과를 한 번 주시해 보십시오.\n\nWe see that some observations lie above and some observations lie below the least squares regression plane.\n우리는 이를 좇으며 몇몇 특정 관측 데이터값 무리들이 유독 최소 제곱 회귀 평면의 궤적 외곽선을 거슬러 더 위쪽에 머무르거나 때로는 반대로 아래로 동떨어져 위치하게 되는 현상을 발견합니다.\n\nIn particular, the linear model seems to overestimate `sales` for instances in which most of the advertising money was spent exclusively on either `TV` or `radio`.\n특히 여기서 선형 모델은 애초 책정된 광고 예산액 중 대부분 목돈이 `TV` 단독이나 아니면 오로지 `radio` 둘 중 어느 한 매체 쪽으로만 아주 독점적일 만치 쏠린 채 지출돼 버린 사례 환경 속에서는 `sales` 예측을 과대평가하는 듯한 아쉬운 모양새를 취하고 맙니다.\n\nIt underestimates `sales` for instances where the budget was split between the two media.\n반면 애당초 예산이 이 두 매체 사이로 분할 양분되어 편성 지출된 인스턴스 사례들 속에서 모델 부문 산출은 `sales` 예측 수준을 의외로 과소평가 처리합니다.\n\nThis pronounced non-linear pattern suggests a _synergy_ or _interaction_ effect between the advertising media, whereby combining the media together results in a bigger boost to sales than using any single medium.\n이렇듯 확연히 도드라지는 이러한 비선형적인 특유의 패턴 형상은, 단일 매체를 사용할 때보다 두 광고 미디어를 동시에 한데 합쳐 취합 적용 활용하는 과정 속 결과치 산출에 있어 일련의 더 커다란 양질 수준의 매출 극적 상승 효과 부스팅을 양산해 줄 그 무언가 이면의 보이지 않는 특정 _동반 시너지(synergy)_ 내지는 잠재된 _상호작용(interaction)_ 파급 효과 여파가 도사리고 있음을 극명히 암시 조달해 주고 있습니다.\n\nIn Section 3.3.2, we will discuss extending the linear model to accommodate such synergistic effects through the use of interaction terms.\n이어지는 섹션 3.3.2 단락에서는 향후 우리가 종종 거론할 이른바 상호작용 항(interaction terms) 의 여건 활용 도입을 거쳐 이와 같은 복합 시너지 작용 효과성을 통계상 넉넉히 한데 수용해 낼 여력의 선형 모델 체계적 확장안 접근 전략 등을 무게감 있게 논의 구상해 보려 합니다.",
    "3.2 Multiple Linear Regression 89": ""
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("done")
